// Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
package io.example.audio.serialization

import io.example.audio.model.ScoreCursor
import io.example.audio.model.ScoreItemID
import io.github.jiyimeta.sheetmusic.audio.serialization.BinaryReader
import io.github.jiyimeta.sheetmusic.audio.serialization.BinaryWriter

internal object ScoreCursorCodec {
    fun encode(value: ScoreCursor): ByteArray {
        val w = BinaryWriter()
        encodePayload(value, w)
        return w.toByteArray()
    }

    fun encodePayload(value: ScoreCursor, w: BinaryWriter) {
        when (value) {
            is ScoreCursor.Item -> {
                w.writeU8(0u)
                ScoreItemIDCodec.encodePayload(value.arg0, w)
            }
            is ScoreCursor.Beat -> {
                w.writeU8(1u)
                w.writeI32(value.arg0)
                w.writeI32(value.arg1)
            }
        }
    }

    fun decode(data: ByteArray): ScoreCursor {
        val r = BinaryReader(data)
        return decodePayload(r)
    }

    fun decodePayload(r: BinaryReader): ScoreCursor {
        return when (val disc = r.readU8().toInt()) {
                    0 -> ScoreCursor.Item(
                        arg0 = ScoreItemIDCodec.decodePayload(r),
                    )
                    1 -> ScoreCursor.Beat(
                        arg0 = r.readI32(),
                        arg1 = r.readI32(),
                    )
            else -> throw IllegalArgumentException(
                "Unknown ScoreCursor discriminator: $disc",
            )
        }
    }
}
