import SheetMusicFoundation

/// Fixed-stride binary form of a draw program, for handing pages to a
/// JavaScript host.
///
/// `DrawProgram`'s own v6 wire format is generated by the `@WireFormat` family
/// of macros, which frames fields as protobuf-style tag / varint /
/// length-delimited records. Kotlin can read it because the Wirelet Gradle
/// plugin generates a matching decoder; there is no such generator for
/// TypeScript, and hand-writing one against macro framing is a mistake this
/// repository has already made once — see `FontMetricsTable.swift`, whose doc
/// comment records a hand-written producer and a `@WireFormat` reader silently
/// failing to agree. This format exists so the JavaScript side never has to
/// know anything about Wirelet.
///
/// ### Wire layout (v1)
///
/// ```text
/// u32 magic       = 0x534D4446 ("SMDF")
/// u32 version     = 1
/// i32 pageCount
/// i32 stringCount
/// [string] × stringCount:
///     i32 byteLen + UTF-8
/// [page] × pageCount:
///     f64 widthMM
///     f64 heightMM
///     i32 commandCount
///     [command] × commandCount:
///         i32 opcode          — DrawCommand's declaration order, 0…11
///         f64 × 6             — fixed; unused slots are 0
///         i32 stringIndex     — -1 when the opcode carries no string
///         u32 integer         — codepoint, or packed ARGB for setColor
///         i32 fontId          — -1 when the opcode carries no font
/// ```
///
/// All little-endian. Six `f64` slots because `cubicTo` needs six and no opcode
/// needs more; the fixed stride is what lets a `DataView` walk the command array
/// without branching on length. Strings live in a side table, deduplicated, so
/// the command array stays fixed-stride.
///
/// Larger than v6 per command, which is deliberate: these bytes cross from wasm
/// memory into a JavaScript typed array and never touch the network.
public enum DrawProgramFlat {
    public static let magic: UInt32 = 0x534D_4446 // "SMDF"
    public static let version: UInt32 = 1

    /// Bytes per command record: opcode + 6 × f64 + stringIndex + integer + fontId.
    static let commandStride = 4 + 6 * 8 + 4 + 4 + 4

    public enum DecodeError: Error, Equatable {
        case badMagic(UInt32)
        case unsupportedVersion(UInt32)
        case truncated
        case unknownOpcode(Int32)
        case badStringIndex(Int32)
        case badFontID(Int32)
        case invalidUTF8
    }

    // MARK: - Encoding

    public static func encode(pages: [EncodablePage]) -> Data {
        var strings: [String] = []
        var stringIndices: [String: Int32] = [:]
        func intern(_ s: String) -> Int32 {
            if let existing = stringIndices[s] { return existing }
            let index = Int32(strings.count)
            strings.append(s)
            stringIndices[s] = index
            return index
        }

        // Commands are encoded first so the string table is complete before it
        // is written; the reader needs the table up front.
        var commandBlocks: [Data] = []
        commandBlocks.reserveCapacity(pages.count)
        for page in pages {
            var block = Data()
            block.reserveCapacity(page.commands.count * commandStride)
            for command in page.commands {
                appendCommand(command, to: &block, intern: intern)
            }
            commandBlocks.append(block)
        }

        var out = Data()
        appendU32(magic, to: &out)
        appendU32(version, to: &out)
        appendI32(Int32(pages.count), to: &out)
        appendI32(Int32(strings.count), to: &out)
        for s in strings {
            let utf8 = Data(s.utf8)
            appendI32(Int32(utf8.count), to: &out)
            out.append(utf8)
        }
        for (page, block) in zip(pages, commandBlocks) {
            appendF64(page.widthMM, to: &out)
            appendF64(page.heightMM, to: &out)
            appendI32(Int32(page.commands.count), to: &out)
            out.append(block)
        }
        return out
    }

    /// Writes one fixed-stride record. `slots` is padded to six, `stringIndex`
    /// and `fontId` default to -1, `integer` to 0 — so each case below names
    /// only the fields it uses and the stride cannot drift per case.
    private static func appendCommand(
        _ command: DrawCommand,
        to out: inout Data,
        intern: (String) -> Int32,
    ) {
        func write(
            _ opcode: Int32,
            _ slots: [Double] = [],
            stringIndex: Int32 = -1,
            integer: UInt32 = 0,
            fontId: Int32 = -1,
        ) {
            appendI32(opcode, to: &out)
            for i in 0 ..< 6 {
                appendF64(i < slots.count ? slots[i] : 0, to: &out)
            }
            appendI32(stringIndex, to: &out)
            appendU32(integer, to: &out)
            appendI32(fontId, to: &out)
        }

        switch command {
        case let .moveTo(x, y):
            write(0, [x, y])
        case let .lineTo(x, y):
            write(1, [x, y])
        case let .stroke(width):
            write(2, [width])
        case let .fillRect(x, y, w, h):
            write(3, [x, y, w, h])
        case let .glyph(codepoint, x, y, size, fontId):
            write(4, [x, y, size], integer: codepoint, fontId: Int32(fontId.rawValue))
        case let .text(text, x, y, size, fontId):
            write(5, [x, y, size], stringIndex: intern(text), fontId: Int32(fontId.rawValue))
        case let .setColor(argb):
            write(6, integer: argb)
        case let .cubicTo(cx1, cy1, cx2, cy2, x, y):
            write(7, [cx1, cy1, cx2, cy2, x, y])
        case let .stretchedGlyph(codepoint, rightEdgeX, topY, bottomY, fontSize, xScale, fontId):
            write(
                8, [rightEdgeX, topY, bottomY, fontSize, xScale],
                integer: codepoint, fontId: Int32(fontId.rawValue),
            )
        case let .setRotation(radians, pivotX, pivotY):
            write(9, [radians, pivotX, pivotY])
        case let .setDash(onMM, offMM):
            write(10, [onMM, offMM])
        case let .italicText(text, x, y, size, fontId):
            write(11, [x, y, size], stringIndex: intern(text), fontId: Int32(fontId.rawValue))
        case let .setTextStyle(flags):
            write(12, integer: UInt32(flags))
        }
    }

    // MARK: - Byte plumbing

    static func appendU32(_ v: UInt32, to out: inout Data) {
        for i in 0 ..< 4 {
            out.append(UInt8(truncatingIfNeeded: v >> (8 * i)))
        }
    }

    static func appendI32(_ v: Int32, to out: inout Data) {
        appendU32(UInt32(bitPattern: v), to: &out)
    }

    static func appendF64(_ v: Double, to out: inout Data) {
        let bits = v.bitPattern
        for i in 0 ..< 8 {
            out.append(UInt8(truncatingIfNeeded: bits >> (8 * i)))
        }
    }
}
