// Dev-only generator — not a library product.
// Run: swift run GenSMuFLTables
// Reads Tools/smufl/glyphnames-subset.json and emits four Swift files into
// Sources/SheetMusicLayout/Engraving/:
//   SMuFLCodepoints+Noteheads.swift   (codepoint < 0xE260)
//   SMuFLCodepoints+Accidentals.swift (0xE260 … 0xE9FF)
//   SMuFLCodepoints+Lines.swift       (>= 0xEA00)
//   SMuFLCodepoints+ByName.swift      (all 395 names, byName resolver)
import Foundation

// MARK: - Paths (derived from #filePath so the binary is relocatable)

/// #filePath = .../Sources/GenSMuFLTables/main.swift
/// → parent = .../Sources/GenSMuFLTables/
/// → parent = .../Sources/
/// → parent = repo root
let repoRoot = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .deletingLastPathComponent()

let subsetURL = repoRoot
    .appendingPathComponent("Tools/smufl/glyphnames-subset.json")
let engravingDir = repoRoot
    .appendingPathComponent("Sources/SheetMusicLayout/Engraving")

// MARK: - Load subset

let subsetData = try Data(contentsOf: subsetURL)
let allGlyphs = try JSONDecoder().decode([String: UInt32].self, from: subsetData)

// MARK: - Bucket by codepoint range

let noteheadEntries = allGlyphs.filter { $0.value < 0xE260 }
let accidentalEntries = allGlyphs.filter { $0.value >= 0xE260 && $0.value <= 0xE9FF }
let lineEntries = allGlyphs.filter { $0.value >= 0xEA00 }

// MARK: - Emit helpers

let fileHeader = """
// Generated by GenSMuFLTables — do not edit by hand. Run: swift run GenSMuFLTables
// Codepoints are SMuFL facts from Tools/smufl/glyphnames-subset.json (glyphnames.json).
import Foundation
"""

func writeConstantFile(entries: [(String, UInt32)], fileName: String) throws {
    let sorted = entries.sorted { $0.0 < $1.0 }
    var lines: [String] = [fileHeader, "", "extension SMuFLCodepoint {"]
    for (name, cp) in sorted {
        lines.append(String(format: "    public static let %@: UInt32 = 0x%04X", name, cp))
    }
    lines.append("}")
    lines.append("")
    let content = lines.joined(separator: "\n")
    let url = engravingDir.appendingPathComponent(fileName)
    try content.write(to: url, atomically: true, encoding: .utf8)
    print("wrote \(fileName): \(sorted.count) glyphs")
}

// MARK: - Emit the three codepoint files

try writeConstantFile(
    entries: Array(noteheadEntries),
    fileName: "SMuFLCodepoints+Noteheads.swift",
)
try writeConstantFile(
    entries: Array(accidentalEntries),
    fileName: "SMuFLCodepoints+Accidentals.swift",
)
try writeConstantFile(
    entries: Array(lineEntries),
    fileName: "SMuFLCodepoints+Lines.swift",
)

// MARK: - Emit the byName resolver (all 395 entries)

let sortedAll = allGlyphs.sorted { $0.key < $1.key }
var byNameLines: [String] = [fileHeader, "", "extension SMuFLCodepoint {"]
byNameLines.append(
    "    /// SMuFL SymId-name → codepoint, for table-driven glyph resolution.",
)
byNameLines.append("    static let glyphCodepoints: [String: UInt32] = [")
for (name, cp) in sortedAll {
    byNameLines.append(String(format: "        \"%@\": 0x%04X,", name, cp))
}

byNameLines.append("    ]")
byNameLines.append("")
byNameLines.append("    static func byName(_ name: String) -> UInt32? {")
byNameLines.append("        glyphCodepoints[name]")
byNameLines.append("    }")
byNameLines.append("}")
byNameLines.append("")
let byNameContent = byNameLines.joined(separator: "\n")
let byNameURL = engravingDir.appendingPathComponent("SMuFLCodepoints+ByName.swift")
try byNameContent.write(to: byNameURL, atomically: true, encoding: .utf8)
print("wrote SMuFLCodepoints+ByName.swift: \(sortedAll.count) glyphs (byName resolver)")
print("done — total \(allGlyphs.count) glyphs across all files")
