#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicAudioCore
    import SheetMusicCore
    import SheetMusicWireFormat
    import Testing

    struct AudioExportRangeCodecTests {
        private let addr = StaffAddress(partIndex: 0, staffIndexInPart: 0)

        // Wire format (generated by @WireFormatChoice on AudioExportRangeWire):
        //   u8 discriminator
        //     0 = full              (no payload)
        //     1 = currentLoop       (no payload)
        //     2 = region            ScoreCursorWire from + ScoreCursorWire to
        //     3 = regionThroughEnd  ScoreCursorWire from + ScoreItemIDWire last

        @Test
        func decodeFull() throws {
            let range = try AudioExportRangeCodec.decode(Data([0x00]))
            guard case .full = range else {
                Issue.record("expected .full, got \(range)")
                return
            }
        }

        @Test
        func decodeCurrentLoop() throws {
            let range = try AudioExportRangeCodec.decode(Data([0x01]))
            guard case .currentLoop = range else {
                Issue.record("expected .currentLoop, got \(range)")
                return
            }
        }

        @Test
        func regionBeatBeatRoundTrip() throws {
            let original = AudioExportRange.region(
                from: .beat(measureIndex: 0, tickInMeasure: 0),
                to: .beat(measureIndex: 1, tickInMeasure: 240),
            )
            let blob = AudioExportRangeCodec.encode(original)
            let decoded = try AudioExportRangeCodec.decode(blob)
            guard case let .region(from, to) = decoded else {
                Issue.record("expected .region, got \(decoded)")
                return
            }
            #expect(from == .beat(measureIndex: 0, tickInMeasure: 0))
            #expect(to == .beat(measureIndex: 1, tickInMeasure: 240))
        }

        @Test
        func regionThroughEndRoundTrip() throws {
            let noteID = NoteID(
                staff: addr, measureIndex: 3, voiceIndex: 0,
                elementIndex: 2, noteIndexInChord: 0,
            )
            let original = AudioExportRange.regionThroughEnd(
                from: .beat(measureIndex: 0, tickInMeasure: 0),
                last: .note(noteID),
            )
            let blob = AudioExportRangeCodec.encode(original)
            let decoded = try AudioExportRangeCodec.decode(blob)
            guard case let .regionThroughEnd(from, last) = decoded else {
                Issue.record("expected .regionThroughEnd, got \(decoded)")
                return
            }
            #expect(from == .beat(measureIndex: 0, tickInMeasure: 0))
            #expect(last == .note(noteID))
        }

        @Test
        func regionThroughEndIs35Bytes() {
            // discriminator(1) + ScoreCursor.beat(9) + ScoreItemID.note(25) = 35 bytes.
            let noteID = NoteID(
                staff: addr, measureIndex: 0, voiceIndex: 0,
                elementIndex: 0, noteIndexInChord: 0,
            )
            let blob = AudioExportRangeCodec.encode(
                .regionThroughEnd(
                    from: .beat(measureIndex: 0, tickInMeasure: 0),
                    last: .note(noteID),
                ),
            )
            #expect(blob.count == 35)
        }

        @Test
        func unknownDiscriminatorThrows() {
            #expect(throws: WireFormatError.self) {
                _ = try AudioExportRangeCodec.decode(Data([0xFF]))
            }
        }
    }
#endif
