#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicCore
    import Testing
    import Wirelet

    struct ClefAnchorCodecTests {
        private let addr = StaffAddress(partIndex: 0, staffIndexInPart: 1)

        // Wire format (generated by @WireFormatChoice on ClefAnchorWire):
        //   u8 discriminator (0 = explicit, 1 = staffDefault)
        //   case 0: VoiceElementIDWire (20 bytes) → total 21 bytes
        //   case 1: StaffAddressWire   (8 bytes)  → total  9 bytes

        @Test
        func explicitIs21Bytes() {
            let id = VoiceElementID(staff: addr, measureIndex: 0, voiceIndex: 0, elementIndex: 0)
            #expect(ClefAnchorCodec.encode(.explicit(id)).count == 21)
        }

        @Test
        func staffDefaultIs9Bytes() {
            #expect(ClefAnchorCodec.encode(.staffDefault(addr)).count == 9)
        }

        @Test
        func explicitDiscriminatorIsZero() {
            let id = VoiceElementID(staff: addr, measureIndex: 1, voiceIndex: 0, elementIndex: 2)
            #expect(ClefAnchorCodec.encode(.explicit(id))[0] == 0x00)
        }

        @Test
        func staffDefaultDiscriminatorIsOne() {
            #expect(ClefAnchorCodec.encode(.staffDefault(addr))[0] == 0x01)
        }

        @Test
        func explicitRoundTrip() throws {
            let id = VoiceElementID(staff: addr, measureIndex: 3, voiceIndex: 1, elementIndex: 7)
            let original = ClefAnchor.explicit(id)
            let decoded = try ClefAnchorCodec.decode(ClefAnchorCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func staffDefaultRoundTrip() throws {
            let original = ClefAnchor.staffDefault(addr)
            let decoded = try ClefAnchorCodec.decode(ClefAnchorCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func unknownDiscriminatorThrows() {
            #expect(throws: WireFormatError.self) {
                _ = try ClefAnchorCodec.decode(Data([0xFF]))
            }
        }

        @Test
        func explicitKnownBytes() {
            let id = VoiceElementID(
                staff: StaffAddress(partIndex: 0, staffIndexInPart: 1),
                measureIndex: 0,
                voiceIndex: 0,
                elementIndex: 0,
            )
            let expected = Data([
                0x00, // discriminator = explicit
                0x00, 0x00, 0x00, 0x00, // partIndex = 0
                0x01, 0x00, 0x00, 0x00, // staffIndexInPart = 1
                0x00, 0x00, 0x00, 0x00, // measureIndex = 0
                0x00, 0x00, 0x00, 0x00, // voiceIndex = 0
                0x00, 0x00, 0x00, 0x00, // elementIndex = 0
            ])
            #expect(ClefAnchorCodec.encode(.explicit(id)) == expected)
        }

        @Test
        func staffDefaultKnownBytes() {
            let a = StaffAddress(partIndex: 2, staffIndexInPart: 0)
            let expected = Data([
                0x01, // discriminator = staffDefault
                0x02, 0x00, 0x00, 0x00, // partIndex = 2
                0x00, 0x00, 0x00, 0x00, // staffIndexInPart = 0
            ])
            #expect(ClefAnchorCodec.encode(.staffDefault(a)) == expected)
        }
    }
#endif
