#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    @testable import SheetMusicAudioCore
    import SheetMusicCore
    import Testing

    struct FrameCodecTests {
        private let addr = StaffAddress(partIndex: 0, staffIndexInPart: 0)

        // Wire format (generated by @WireFormat on FrameWire):
        //   i64 tick
        //   f64 timeSeconds              ← IEEE 754 raw (no scaling)
        //   ScoreCursorWire (variable)

        @Test
        func beatFrameRoundTrip() throws {
            let original = PlaybackTimeline.Frame(
                tick: 480,
                timeSeconds: 0.5,
                cursor: .beat(measureIndex: 0, tickInMeasure: 480),
            )
            let decoded = try FrameCodec.decode(FrameCodec.encode(original))
            #expect(decoded.tick == original.tick)
            #expect(decoded.timeSeconds == original.timeSeconds)
            #expect(decoded.cursor == original.cursor)
        }

        @Test
        func itemFrameRoundTrip() throws {
            let noteID = NoteID(
                staff: addr, measureIndex: 2, voiceIndex: 0,
                elementIndex: 1, noteIndexInChord: 0,
            )
            let original = PlaybackTimeline.Frame(
                tick: 960,
                timeSeconds: 1.0,
                cursor: .item(.note(noteID)),
            )
            let decoded = try FrameCodec.decode(FrameCodec.encode(original))
            #expect(decoded.tick == original.tick)
            #expect(decoded.timeSeconds == original.timeSeconds)
            #expect(decoded.cursor == original.cursor)
        }

        @Test
        func timeSecondsExactRoundTrip() throws {
            // Raw Double round-trip is bit-identical for representable values.
            let original = PlaybackTimeline.Frame(
                tick: 100, timeSeconds: 1.23456789,
                cursor: .beat(measureIndex: 0, tickInMeasure: 0),
            )
            let decoded = try FrameCodec.decode(FrameCodec.encode(original))
            #expect(decoded.timeSeconds == original.timeSeconds)
        }

        @Test
        func knownBytesTickLEPrefix() {
            // tick=1 → first 8 bytes are i64 LE = [0x01, 0x00 × 7]
            let frame = PlaybackTimeline.Frame(
                tick: 1, timeSeconds: 0.0,
                cursor: .beat(measureIndex: 0, tickInMeasure: 0),
            )
            let blob = FrameCodec.encode(frame)
            #expect(blob[0] == 0x01)
            #expect(blob[1] == 0x00)
            #expect(blob[7] == 0x00)
        }
    }
#endif
