#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicAudioCore
    import SheetMusicCore
    import Testing

    struct MetronomeBeatCodecTests {
        // Wire layout (generated by @WireFormat on MetronomeBeatWire):
        //   i32 count
        //   count × { i64 tick, u8 isDownbeat }   9 bytes per entry

        @Test
        func emptyArrayRoundTrip() throws {
            let blob = MetronomeBeatCodec.encodeArray([])
            let decoded = try MetronomeBeatCodec.decodeArray(blob)
            #expect(decoded.isEmpty)
        }

        @Test
        func singleDownbeatRoundTrip() throws {
            let beat = MetronomeBeat(tick: 0, isDownbeat: true)
            let blob = MetronomeBeatCodec.encodeArray([beat])
            let decoded = try MetronomeBeatCodec.decodeArray(blob)
            #expect(decoded.count == 1)
            #expect(decoded[0].tick == 0)
            #expect(decoded[0].isDownbeat == true)
        }

        @Test
        func singleUpbeatRoundTrip() throws {
            let beat = MetronomeBeat(tick: 480, isDownbeat: false)
            let blob = MetronomeBeatCodec.encodeArray([beat])
            let decoded = try MetronomeBeatCodec.decodeArray(blob)
            #expect(decoded.count == 1)
            #expect(decoded[0].tick == 480)
            #expect(decoded[0].isDownbeat == false)
        }

        @Test
        func multipleBeatsRoundTrip() throws {
            let beats = [
                MetronomeBeat(tick: 0, isDownbeat: true),
                MetronomeBeat(tick: 480, isDownbeat: false),
                MetronomeBeat(tick: 960, isDownbeat: false),
                MetronomeBeat(tick: 1440, isDownbeat: false),
                MetronomeBeat(tick: 1920, isDownbeat: true),
            ]
            let blob = MetronomeBeatCodec.encodeArray(beats)
            let decoded = try MetronomeBeatCodec.decodeArray(blob)
            #expect(decoded == beats)
        }

        @Test
        func entrySize9Bytes() {
            // 4 (count) + 1 * 9 (entry: tick i64 + isDownbeat u8) = 13 bytes
            let beat = MetronomeBeat(tick: 0, isDownbeat: true)
            let blob = MetronomeBeatCodec.encodeArray([beat])
            #expect(blob.count == 13)
        }

        @Test
        func knownBytesDownbeat() {
            // tick=1, isDownbeat=true → u8(1)
            // [1,0,0,0] count=1, [1,0,0,0,0,0,0,0] tick=1, [1] isDownbeat=true
            let beat = MetronomeBeat(tick: 1, isDownbeat: true)
            let blob = MetronomeBeatCodec.encodeArray([beat])
            let expected = Data([
                0x01, 0x00, 0x00, 0x00, // count=1
                0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // tick=1
                0x01, // isDownbeat=true
            ])
            #expect(blob == expected)
        }

        @Test
        func knownBytesUpbeat() {
            // count[0..3] + tick[4..11] + isDownbeat[12]
            let beat = MetronomeBeat(tick: 480, isDownbeat: false)
            let blob = MetronomeBeatCodec.encodeArray([beat])
            #expect(blob[12] == 0x00) // isDownbeat=false
        }
    }
#endif
