#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicCore
    import SheetMusicWireFormat
    import Testing

    struct ScoreItemIDCodecTests {
        private let addr = StaffAddress(partIndex: 0, staffIndexInPart: 0)

        // Wire format (generated by @WireFormatChoice on ScoreItemIDWire):
        //   u8 discriminator (0 = note, 1 = rest, 2 = tuplet, 3 = clef)
        //   case 0: NoteIDWire    (24 bytes)
        //   case 1: RestIDWire    (20 bytes)
        //   case 2: TupletIDWire  (20 bytes)
        //   case 3: ClefAnchorWire (variable)

        @Test
        func noteIs25Bytes() {
            let id = ScoreItemID.note(NoteID(
                staff: addr, measureIndex: 0, voiceIndex: 0,
                elementIndex: 0, noteIndexInChord: 0,
            ))
            #expect(ScoreItemIDCodec.encode(id).count == 25)
        }

        @Test
        func restIs21Bytes() {
            let id = ScoreItemID.rest(RestID(
                staff: addr, measureIndex: 0, voiceIndex: 0, elementIndex: 0,
            ))
            #expect(ScoreItemIDCodec.encode(id).count == 21)
        }

        @Test
        func tupletIs21Bytes() {
            let id = ScoreItemID.tuplet(TupletID(
                staff: addr, measureIndex: 0, voiceIndex: 0, startElementIndex: 0,
            ))
            #expect(ScoreItemIDCodec.encode(id).count == 21)
        }

        @Test
        func clefExplicitIs22Bytes() {
            let veid = VoiceElementID(
                staff: addr, measureIndex: 0, voiceIndex: 0, elementIndex: 0,
            )
            let id = ScoreItemID.clef(.explicit(veid))
            #expect(ScoreItemIDCodec.encode(id).count == 22)
        }

        @Test
        func clefStaffDefaultIs10Bytes() {
            let id = ScoreItemID.clef(.staffDefault(addr))
            #expect(ScoreItemIDCodec.encode(id).count == 10)
        }

        @Test
        func noteDiscriminatorIsZero() {
            let id = ScoreItemID.note(NoteID(
                staff: addr, measureIndex: 0, voiceIndex: 0,
                elementIndex: 0, noteIndexInChord: 0,
            ))
            #expect(ScoreItemIDCodec.encode(id)[0] == 0x00)
        }

        @Test
        func restDiscriminatorIsOne() {
            let id = ScoreItemID.rest(RestID(
                staff: addr, measureIndex: 0, voiceIndex: 0, elementIndex: 0,
            ))
            #expect(ScoreItemIDCodec.encode(id)[0] == 0x01)
        }

        @Test
        func tupletDiscriminatorIsTwo() {
            let id = ScoreItemID.tuplet(TupletID(
                staff: addr, measureIndex: 0, voiceIndex: 0, startElementIndex: 0,
            ))
            #expect(ScoreItemIDCodec.encode(id)[0] == 0x02)
        }

        @Test
        func clefDiscriminatorIsThree() {
            let id = ScoreItemID.clef(.staffDefault(addr))
            #expect(ScoreItemIDCodec.encode(id)[0] == 0x03)
        }

        @Test
        func noteRoundTrip() throws {
            let original = ScoreItemID.note(NoteID(
                staff: addr, measureIndex: 5, voiceIndex: 0,
                elementIndex: 3, noteIndexInChord: 1,
            ))
            let decoded = try ScoreItemIDCodec.decode(ScoreItemIDCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func restRoundTrip() throws {
            let original = ScoreItemID.rest(RestID(
                staff: addr, measureIndex: 2, voiceIndex: 1, elementIndex: 0,
            ))
            let decoded = try ScoreItemIDCodec.decode(ScoreItemIDCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func tupletRoundTrip() throws {
            let original = ScoreItemID.tuplet(TupletID(
                staff: addr, measureIndex: 1, voiceIndex: 0, startElementIndex: 4,
            ))
            let decoded = try ScoreItemIDCodec.decode(ScoreItemIDCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func clefExplicitRoundTrip() throws {
            let veid = VoiceElementID(
                staff: StaffAddress(partIndex: 1, staffIndexInPart: 0),
                measureIndex: 0, voiceIndex: 0, elementIndex: 2,
            )
            let original = ScoreItemID.clef(.explicit(veid))
            let decoded = try ScoreItemIDCodec.decode(ScoreItemIDCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func clefStaffDefaultRoundTrip() throws {
            let original = ScoreItemID.clef(.staffDefault(addr))
            let decoded = try ScoreItemIDCodec.decode(ScoreItemIDCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func emptyArrayRoundTrip() throws {
            let blob = ScoreItemIDCodec.encodeArray([])
            let decoded = try ScoreItemIDCodec.decodeArray(blob)
            #expect(decoded.isEmpty)
        }

        @Test
        func arrayRoundTrip() throws {
            let items: [ScoreItemID] = [
                .note(NoteID(staff: addr, measureIndex: 0, voiceIndex: 0, elementIndex: 0, noteIndexInChord: 0)),
                .rest(RestID(staff: addr, measureIndex: 1, voiceIndex: 0, elementIndex: 2)),
                .clef(.staffDefault(addr)),
            ]
            let blob = ScoreItemIDCodec.encodeArray(items)
            let decoded = try ScoreItemIDCodec.decodeArray(blob)
            #expect(decoded == items)
        }
    }
#endif
