#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicCore
    import Testing
    import Wirelet

    struct ScoreCursorCodecTests {
        private let addr = StaffAddress(partIndex: 0, staffIndexInPart: 0)

        // Wire format (generated by @WireFormatChoice on ScoreCursorWire):
        //   u8 discriminator (0 = item, 1 = beat)
        //   case 0: ScoreItemIDWire (variable)
        //   case 1: i32 measureIndex + i32 tickInMeasure → total 9 bytes

        @Test
        func itemCursorDiscriminatorIsZero() {
            let noteID = NoteID(
                staff: addr, measureIndex: 0, voiceIndex: 0,
                elementIndex: 0, noteIndexInChord: 0,
            )
            let blob = ScoreCursorCodec.encode(.item(.note(noteID)))
            #expect(blob[0] == 0x00)
        }

        @Test
        func beatCursorDiscriminatorIsOne() {
            let blob = ScoreCursorCodec.encode(.beat(measureIndex: 0, tickInMeasure: 0))
            #expect(blob[0] == 0x01)
        }

        @Test
        func beatCursorIs9Bytes() {
            let blob = ScoreCursorCodec.encode(.beat(measureIndex: 5, tickInMeasure: 480))
            #expect(blob.count == 9)
        }

        @Test
        func beatCursorKnownBytes() {
            let blob = ScoreCursorCodec.encode(.beat(measureIndex: 3, tickInMeasure: 960))
            let expected = Data([
                0x01, // discriminator = beat
                0x03, 0x00, 0x00, 0x00, // measureIndex = 3
                0xC0, 0x03, 0x00, 0x00, // tickInMeasure = 960
            ])
            #expect(blob == expected)
        }

        @Test
        func itemNoteRoundTrip() throws {
            let noteID = NoteID(
                staff: addr, measureIndex: 2, voiceIndex: 0,
                elementIndex: 1, noteIndexInChord: 0,
            )
            let original = ScoreCursor.item(.note(noteID))
            let decoded = try ScoreCursorCodec.decode(ScoreCursorCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func itemRestRoundTrip() throws {
            let restID = RestID(staff: addr, measureIndex: 0, voiceIndex: 1, elementIndex: 3)
            let original = ScoreCursor.item(.rest(restID))
            let decoded = try ScoreCursorCodec.decode(ScoreCursorCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func beatRoundTrip() throws {
            let original = ScoreCursor.beat(measureIndex: 7, tickInMeasure: 1920)
            let decoded = try ScoreCursorCodec.decode(ScoreCursorCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func unknownDiscriminatorThrows() {
            #expect(throws: WireFormatError.self) {
                _ = try ScoreCursorCodec.decode(Data([0xFF]))
            }
        }
    }
#endif
