#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicCore
    import Testing

    struct StaffParamsCodecTests {
        // Wire layout (generated by @WireFormat on StaffParamsWire):
        //   i32 count
        //   count × { i32 staffIndex; u8 bankLSB; u8 program; u8 isDrums;
        //             i64 partAddressHash }    15 bytes per entry

        @Test
        func emptyArrayRoundTrip() throws {
            let blob = StaffParamsCodec.encodeArray([])
            let decoded = try StaffParamsCodec.decodeArray(blob)
            #expect(decoded.isEmpty)
        }

        @Test
        func singleEntryRoundTrip() throws {
            let params = StaffParams(
                staffIndex: 0,
                bankLSB: 0,
                program: 40,
                isDrums: false,
                partAddressHash: 0,
            )
            let blob = StaffParamsCodec.encodeArray([params])
            let decoded = try StaffParamsCodec.decodeArray(blob)
            #expect(decoded.count == 1)
            #expect(decoded[0] == params)
        }

        @Test
        func drumChannelRoundTrip() throws {
            let params = StaffParams(
                staffIndex: 2,
                bankLSB: 0,
                program: 0,
                isDrums: true,
                partAddressHash: 42,
            )
            let blob = StaffParamsCodec.encodeArray([params])
            let decoded = try StaffParamsCodec.decodeArray(blob)
            #expect(decoded.count == 1)
            #expect(decoded[0].isDrums == true)
            #expect(decoded[0].staffIndex == 2)
            #expect(decoded[0].partAddressHash == 42)
        }

        @Test
        func multipleEntriesRoundTrip() throws {
            let entries = [
                StaffParams(
                    staffIndex: 0, bankLSB: 0, program: 0,
                    isDrums: false, partAddressHash: 1000,
                ),
                StaffParams(
                    staffIndex: 1, bankLSB: 0, program: 40,
                    isDrums: false, partAddressHash: 1001,
                ),
                StaffParams(
                    staffIndex: 2, bankLSB: 0, program: 0,
                    isDrums: true, partAddressHash: 2000,
                ),
            ]
            let blob = StaffParamsCodec.encodeArray(entries)
            let decoded = try StaffParamsCodec.decodeArray(blob)
            #expect(decoded == entries)
        }

        @Test
        func entrySize15Bytes() {
            // 4 (count) + 15 (entry) = 19 bytes
            let params = StaffParams(
                staffIndex: 0, bankLSB: 0, program: 0,
                isDrums: false, partAddressHash: 0,
            )
            let blob = StaffParamsCodec.encodeArray([params])
            #expect(blob.count == 19)
        }

        @Test
        func knownBytesEntry() {
            // staffIndex=1, bankLSB=2, program=40, isDrums=false, partAddressHash=0x0102030405060708
            let params = StaffParams(
                staffIndex: 1,
                bankLSB: 2,
                program: 40,
                isDrums: false,
                partAddressHash: 0x0102_0304_0506_0708,
            )
            let blob = StaffParamsCodec.encodeArray([params])
            let expected = Data([
                0x01, 0x00, 0x00, 0x00, // count=1
                0x01, 0x00, 0x00, 0x00, // staffIndex=1
                0x02, // bankLSB=2
                0x28, // program=40 (0x28)
                0x00, // isDrums=false
                0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, // hash LE
            ])
            #expect(blob == expected)
        }
    }
#endif
