#if !os(Android)
    import Foundation
    @testable import SheetMusicAndroidJNI
    import SheetMusicCore
    import SheetMusicWireFormat
    import Testing

    struct StaffAddressCodecTests {
        // Wire format (generated by @WireFormat on StaffAddressWire):
        //   i32 partIndex + i32 staffIndexInPart = 8 bytes

        @Test
        func encodeProducesEightBytes() {
            let addr = StaffAddress(partIndex: 0, staffIndexInPart: 0)
            #expect(StaffAddressCodec.encode(addr).count == 8)
        }

        @Test
        func encodeKnownBytes() {
            let addr = StaffAddress(partIndex: 1, staffIndexInPart: 2)
            #expect(
                StaffAddressCodec.encode(addr) ==
                    Data([0x01, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00]),
            )
        }

        @Test
        func encodeNegativeIndicesAllowed() {
            let addr = StaffAddress(partIndex: -1, staffIndexInPart: 0)
            #expect(StaffAddressCodec.encode(addr).prefix(4) == Data([0xFF, 0xFF, 0xFF, 0xFF]))
        }

        @Test
        func roundTripZero() throws {
            let original = StaffAddress(partIndex: 0, staffIndexInPart: 0)
            let decoded = try StaffAddressCodec.decode(StaffAddressCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func roundTripNonZero() throws {
            let original = StaffAddress(partIndex: 3, staffIndexInPart: 7)
            let decoded = try StaffAddressCodec.decode(StaffAddressCodec.encode(original))
            #expect(decoded == original)
        }

        @Test
        func decodeUnderflowThrows() {
            #expect(throws: WireFormatError.self) {
                _ = try StaffAddressCodec.decode(Data([0x01, 0x00, 0x00])) // 3 bytes only
            }
        }
    }
#endif
