package io.github.jiyimeta.sheetmusic.audio.serialization

import io.github.jiyimeta.sheetmusic.audio.model.AudioExportRange
import io.github.jiyimeta.sheetmusic.audio.model.NoteID
import io.github.jiyimeta.sheetmusic.audio.model.ScoreCursor
import io.github.jiyimeta.sheetmusic.audio.model.ScoreItemID
import io.github.jiyimeta.sheetmusic.audio.model.StaffAddress
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test

// Wire format (no version envelope; generated by Swift's @WireFormatChoice
// on AudioExportRangeWire):
//   u8 discriminator
//     0 = Full              (no payload)
//     1 = CurrentLoop       (no payload)
//     2 = Region            ScoreCursor(from) + ScoreCursor(to)
//     3 = RegionThroughEnd  ScoreCursor(from) + ScoreItemID(last)
class AudioExportRangeEncoderTest {
    @Test fun encodesFullAsTagZero() {
        val bytes = AudioExportRangeEncoder.encode(AudioExportRange.Full)
        assertArrayEquals(byteArrayOf(0x00), bytes)
    }

    @Test fun encodesCurrentLoopAsTagOne() {
        val bytes = AudioExportRangeEncoder.encode(AudioExportRange.CurrentLoop)
        assertArrayEquals(byteArrayOf(0x01), bytes)
    }

    @Test fun encodesRegionWithCursorPair() {
        val from = ScoreCursor.Beat(measureIndex = 0, tickInMeasure = 0)
        val to = ScoreCursor.Beat(measureIndex = 1, tickInMeasure = 240)
        val bytes = AudioExportRangeEncoder.encode(AudioExportRange.Region(from, to))

        // tag(1) + ScoreCursor.Beat × 2 (each 9 bytes) = 19 bytes.
        assertEquals(0x02.toByte(), bytes[0])
        assertEquals(1 + 9 + 9, bytes.size)

        val expectedFromPayload = byteArrayOf(
            0x01, // ScoreCursor.Beat discriminator
            0x00, 0x00, 0x00, 0x00, // measureIndex = 0
            0x00, 0x00, 0x00, 0x00, // tickInMeasure = 0
        )
        val expectedToPayload = byteArrayOf(
            0x01, // ScoreCursor.Beat discriminator
            0x01, 0x00, 0x00, 0x00, // measureIndex = 1
            0xF0.toByte(), 0x00, 0x00, 0x00, // tickInMeasure = 240
        )
        assertArrayEquals(expectedFromPayload, bytes.copyOfRange(1, 10))
        assertArrayEquals(expectedToPayload, bytes.copyOfRange(10, 19))
    }

    @Test fun encodesRegionThroughEndWithCursorAndItemID() {
        val from = ScoreCursor.Beat(measureIndex = 0, tickInMeasure = 0)
        val last = ScoreItemID.Note(
            NoteID(
                staff = StaffAddress(partIndex = 0, staffIndexInPart = 0),
                measureIndex = 1,
                voiceIndex = 0,
                elementIndex = 3,
                noteIndexInChord = 0,
            ),
        )
        val bytes = AudioExportRangeEncoder.encode(AudioExportRange.RegionThroughEnd(from, last))

        // tag(1) + Beat cursor(9) + ScoreItemID.Note(1 + 24) = 35 bytes.
        assertEquals(0x03.toByte(), bytes[0])
        assertEquals(1 + 9 + 1 + 24, bytes.size)

        // ScoreItemID.Note discriminator at offset 10 (after tag + Beat cursor 9).
        assertEquals(0x00.toByte(), bytes[10])

        val expectedNoteIDBody = byteArrayOf(
            0x00, 0x00, 0x00, 0x00, // partIndex = 0
            0x00, 0x00, 0x00, 0x00, // staffIndexInPart = 0
            0x01, 0x00, 0x00, 0x00, // measureIndex = 1
            0x00, 0x00, 0x00, 0x00, // voiceIndex = 0
            0x03, 0x00, 0x00, 0x00, // elementIndex = 3
            0x00, 0x00, 0x00, 0x00, // noteIndexInChord = 0
        )
        assertArrayEquals(expectedNoteIDBody, bytes.copyOfRange(11, 35))
    }
}
