import Foundation
import SheetMusicAudioCore
import SheetMusicCore
import Wirelet

/// Codec for `AudioExportRange` — Kotlin → Swift direction. The encoder
/// lives on the Kotlin side (the host requests the range); Swift only
/// decodes here.
///
/// Wire layout (generated by `@WireFormatChoice` on `AudioExportRangeWire`):
/// ```
/// u8 discriminator   0=full, 1=currentLoop, 2=region, 3=regionThroughEnd
/// case 0 / 1: (no payload)
/// case 2: ScoreCursorWire from + ScoreCursorWire to
/// case 3: ScoreCursorWire from + ScoreItemIDWire last
/// ```
///
/// No version envelope.
public enum AudioExportRangeCodec {
    public static func encode(_ value: AudioExportRange) -> Data {
        AudioExportRangeWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> AudioExportRange {
        try AudioExportRangeWire(decoding: data).decoded()
    }
}

@WireFormatChoice
enum AudioExportRangeWire {
    case full
    case currentLoop
    case region(ScoreCursorWire, ScoreCursorWire)
    case regionThroughEnd(ScoreCursorWire, ScoreItemIDWire)

    init(from value: AudioExportRange) {
        switch value {
        case .full:
            self = .full
        case .currentLoop:
            self = .currentLoop
        case let .region(from, to):
            self = .region(
                ScoreCursorWire(from: from),
                ScoreCursorWire(from: to),
            )
        case let .regionThroughEnd(from, last):
            self = .regionThroughEnd(
                ScoreCursorWire(from: from),
                ScoreItemIDWire(from: last),
            )
        }
    }

    func decoded() -> AudioExportRange {
        switch self {
        case .full:
            return .full
        case .currentLoop:
            return .currentLoop
        case let .region(from, to):
            return .region(from: from.decoded(), to: to.decoded())
        case let .regionThroughEnd(from, last):
            return .regionThroughEnd(from: from.decoded(), last: last.decoded())
        }
    }
}
