import Foundation
import SheetMusicCore
import Wirelet

/// Codec for `ClefAnchor` — a sum-type variable-length payload.
///
/// Wire layout (generated by `@WireFormatChoice` on `ClefAnchorWire`):
/// ```
/// u8 discriminator                 0 = explicit, 1 = staffDefault
/// case 0: VoiceElementIDWire (20)  → total 21 bytes
/// case 1: StaffAddressWire    (8)  → total  9 bytes
/// ```
public enum ClefAnchorCodec {
    public static func encode(_ value: ClefAnchor) -> Data {
        ClefAnchorWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> ClefAnchor {
        try ClefAnchorWire(decoding: data).decoded()
    }
}

@WireFormatChoice
enum ClefAnchorWire {
    case explicit(VoiceElementIDWire)
    case staffDefault(StaffAddressWire)

    init(from value: ClefAnchor) {
        switch value {
        case let .explicit(id):
            self = .explicit(VoiceElementIDWire(from: id))
        case let .staffDefault(staff):
            self = .staffDefault(StaffAddressWire(from: staff))
        }
    }

    func decoded() -> ClefAnchor {
        switch self {
        case let .explicit(wire):
            return .explicit(wire.decoded())
        case let .staffDefault(wire):
            return .staffDefault(wire.decoded())
        }
    }
}
