import Foundation
import SheetMusicAudioCore
import SheetMusicCore
import SheetMusicWireFormat

/// Codec for `PlaybackTimeline.Frame` — a top-level blob.
///
/// Wire layout (generated by `@WireFormat` on `FrameWire`):
/// ```
/// i64 tick
/// f64 timeSeconds              ← IEEE 754 little-endian (raw, no scaling)
/// ScoreCursorWire (variable)
/// ```
///
/// No version envelope.
public enum FrameCodec {
    public static func encode(_ value: PlaybackTimeline.Frame) -> Data {
        FrameWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> PlaybackTimeline.Frame {
        try FrameWire(decoding: data).decoded()
    }
}

@WireFormat
struct FrameWire {
    var tick: Int64
    var timeSeconds: Double
    var cursor: ScoreCursorWire

    init(from value: PlaybackTimeline.Frame) {
        tick = Int64(value.tick)
        timeSeconds = value.timeSeconds
        cursor = ScoreCursorWire(from: value.cursor)
    }

    func decoded() -> PlaybackTimeline.Frame {
        PlaybackTimeline.Frame(
            tick: Int(tick),
            timeSeconds: timeSeconds,
            cursor: cursor.decoded(),
        )
    }
}
