import Foundation
import Wirelet

/// Wire format for the loop-region highlight rectangles. One rect per
/// intersected system, in mm coordinates.
///
/// Bytes layout (generated by `@WireFormat` on `LoopHighlightCodec.Rect`):
/// ```
/// i32 count                ← Array<T> length prefix
/// count × {
///   f64 x                  ← IEEE 754 little-endian
///   f64 y
///   f64 width
///   f64 height
/// }
/// ```
///
/// 32 bytes per rect (was 32 in the i64-micros format too, but values
/// are now raw IEEE 754 instead of micros-scaled). Empty byte array
/// signals "no rects" (loop range empty or unresolved); the encoder
/// always produces the full envelope for a non-nil input, even if the
/// input array is empty (4-byte i32 count = 0).
public enum LoopHighlightCodec {
    @WireFormat
    public struct Rect: Equatable {
        public let x: Double
        public let y: Double
        public let width: Double
        public let height: Double

        public init(x: Double, y: Double, width: Double, height: Double) {
            self.x = x
            self.y = y
            self.width = width
            self.height = height
        }
    }

    public static func encode(_ rects: [Rect]) -> Data {
        rects.encodeToData()
    }

    public static func decode(_ data: Data) throws -> [Rect] {
        if data.isEmpty { return [] }
        return try [Rect](decoding: data)
    }
}
