import Foundation
import SheetMusicCore
import SheetMusicWireFormat

/// Codecs for path-based identity types: `VoiceElementID`, `NoteID`,
/// `RestID`, and `TupletID`. Wire layouts are generated by `@WireFormat`
/// on the per-type `*Wire` mirror structs.
///
/// ```
/// VoiceElementIDWire (20 bytes)
///   StaffAddressWire (8) + i32 measureIndex + i32 voiceIndex + i32 elementIndex
///
/// NoteIDWire (24 bytes)
///   StaffAddressWire (8) + i32 × 4 (measure / voice / element / noteIndexInChord)
///
/// RestIDWire (20 bytes)
///   StaffAddressWire (8) + i32 × 3
///
/// TupletIDWire (20 bytes)
///   StaffAddressWire (8) + i32 measure + i32 voice + i32 startElementIndex
/// ```
///
/// Top-level `NoteID` blob: `NoteIDWire` bytes directly (no version envelope).
public enum PathIDCodecs {
    public static func encode(_ value: NoteID) -> Data {
        NoteIDWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> NoteID {
        try NoteIDWire(decoding: data).decoded()
    }
}

// MARK: - VoiceElementID

@WireFormat
struct VoiceElementIDWire {
    var staff: StaffAddressWire
    var measureIndex: Int32
    var voiceIndex: Int32
    var elementIndex: Int32

    init(from value: VoiceElementID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        elementIndex = Int32(value.elementIndex)
    }

    func decoded() -> VoiceElementID {
        VoiceElementID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            elementIndex: Int(elementIndex),
        )
    }
}

// MARK: - NoteID

@WireFormat
struct NoteIDWire {
    var staff: StaffAddressWire
    var measureIndex: Int32
    var voiceIndex: Int32
    var elementIndex: Int32
    var noteIndexInChord: Int32

    init(from value: NoteID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        elementIndex = Int32(value.elementIndex)
        noteIndexInChord = Int32(value.noteIndexInChord)
    }

    func decoded() -> NoteID {
        NoteID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            elementIndex: Int(elementIndex),
            noteIndexInChord: Int(noteIndexInChord),
        )
    }
}

// MARK: - RestID

@WireFormat
struct RestIDWire {
    var staff: StaffAddressWire
    var measureIndex: Int32
    var voiceIndex: Int32
    var elementIndex: Int32

    init(from value: RestID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        elementIndex = Int32(value.elementIndex)
    }

    func decoded() -> RestID {
        RestID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            elementIndex: Int(elementIndex),
        )
    }
}

// MARK: - TupletID

@WireFormat
struct TupletIDWire {
    var staff: StaffAddressWire
    var measureIndex: Int32
    var voiceIndex: Int32
    var startElementIndex: Int32

    init(from value: TupletID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        startElementIndex = Int32(value.startElementIndex)
    }

    func decoded() -> TupletID {
        TupletID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            startElementIndex: Int(startElementIndex),
        )
    }
}
