import Foundation
import SheetMusicCore
import Wirelet

/// Codec for `ScoreItemID` — a sum-type variable-length payload, plus
/// top-level single + array blobs.
///
/// Wire layout (generated by `@WireFormatChoice` on `ScoreItemIDWire`):
/// ```
/// u8 discriminator    0=note, 1=rest, 2=tuplet, 3=clef
/// case 0: NoteIDWire    (24) → total 25 bytes
/// case 1: RestIDWire    (20) → total 21 bytes
/// case 2: TupletIDWire  (20) → total 21 bytes
/// case 3: ClefAnchorWire (variable)
/// ```
///
/// Top-level single: `ScoreItemIDWire` directly (no version envelope).
/// Array: `i32 count + count × ScoreItemIDWire` via `Array<T: WireFormat>`.
public enum ScoreItemIDCodec {
    public static func encode(_ value: ScoreItemID) -> Data {
        ScoreItemIDWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> ScoreItemID {
        try ScoreItemIDWire(decoding: data).decoded()
    }

    public static func encodeArray(_ values: [ScoreItemID]) -> Data {
        values.map(ScoreItemIDWire.init(from:)).encodeToData()
    }

    public static func decodeArray(_ data: Data) throws -> [ScoreItemID] {
        try [ScoreItemIDWire](decoding: data).map { $0.decoded() }
    }
}

@WireFormatChoice
enum ScoreItemIDWire {
    case note(NoteIDWire)
    case rest(RestIDWire)
    case tuplet(TupletIDWire)
    case clef(ClefAnchorWire)

    init(from value: ScoreItemID) {
        switch value {
        case let .note(id):
            self = .note(NoteIDWire(from: id))
        case let .rest(id):
            self = .rest(RestIDWire(from: id))
        case let .tuplet(id):
            self = .tuplet(TupletIDWire(from: id))
        case let .clef(anchor):
            self = .clef(ClefAnchorWire(from: anchor))
        }
    }

    func decoded() -> ScoreItemID {
        switch self {
        case let .note(wire): return .note(wire.decoded())
        case let .rest(wire): return .rest(wire.decoded())
        case let .tuplet(wire): return .tuplet(wire.decoded())
        case let .clef(wire): return .clef(wire.decoded())
        }
    }
}
