import Foundation
import SheetMusicCore
import Wirelet

/// Codec for `ScoreCursor` — a sum-type variable-length payload, plus
/// a top-level blob.
///
/// Wire layout (generated by `@WireFormatChoice` on `ScoreCursorWire`):
/// ```
/// u8 discriminator   0 = item, 1 = beat
/// case 0: ScoreItemIDWire (variable)
/// case 1: i32 measureIndex + i32 tickInMeasure   → total 9 bytes
/// ```
///
/// Top-level: `ScoreCursorWire` directly (no version envelope).
public enum ScoreCursorCodec {
    public static func encode(_ value: ScoreCursor) -> Data {
        ScoreCursorWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> ScoreCursor {
        try ScoreCursorWire(decoding: data).decoded()
    }
}

@WireFormatChoice
enum ScoreCursorWire {
    case item(ScoreItemIDWire)
    case beat(measureIndex: Int32, tickInMeasure: Int32)

    init(from value: ScoreCursor) {
        switch value {
        case let .item(itemID):
            self = .item(ScoreItemIDWire(from: itemID))
        case let .beat(measureIndex, tickInMeasure):
            self = .beat(
                measureIndex: Int32(measureIndex),
                tickInMeasure: Int32(tickInMeasure),
            )
        }
    }

    func decoded() -> ScoreCursor {
        switch self {
        case let .item(wire):
            return .item(wire.decoded())
        case let .beat(measureIndex, tickInMeasure):
            return .beat(
                measureIndex: Int(measureIndex),
                tickInMeasure: Int(tickInMeasure),
            )
        }
    }
}
