import Foundation
import SheetMusicCore
import Wirelet

/// Codec for `StaffAddress` — an 8-byte fixed-size payload.
///
/// Wire layout (generated by `@WireFormat` on `StaffAddressWire`):
/// ```
/// i32 partIndex
/// i32 staffIndexInPart
/// ```
public enum StaffAddressCodec {
    public static func encode(_ value: StaffAddress) -> Data {
        StaffAddressWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> StaffAddress {
        try StaffAddressWire(decoding: data).decoded()
    }
}

@WireFormat
public struct StaffAddressWire {
    public var partIndex: Int32
    public var staffIndexInPart: Int32

    public init(from value: StaffAddress) {
        partIndex = Int32(value.partIndex)
        staffIndexInPart = Int32(value.staffIndexInPart)
    }

    public func decoded() -> StaffAddress {
        StaffAddress(
            partIndex: Int(partIndex),
            staffIndexInPart: Int(staffIndexInPart),
        )
    }
}
