import Foundation
import SheetMusicCore
import SheetMusicWireFormat

/// Instrument/channel parameters for one staff, passed across the JNI
/// boundary so Kotlin can configure the Android audio engine.
///
/// `partAddressHash` is a deterministic Int64 fingerprint of the owning
/// `StaffAddress`. The Kotlin side treats it as opaque; it is used only
/// for change-detection. The formula is:
/// ```
///   Int64(partIndex) * 1_000 + Int64(staffIndexInPart)
/// ```
/// This is sufficient for the v0 scope (≤ 1000 staves per part, which
/// covers all practical scores).
public struct StaffParams: Equatable, Sendable {
    public let staffIndex: Int
    public let bankLSB: UInt8
    public let program: UInt8
    public let isDrums: Bool
    /// Opaque Int64 fingerprint of the owning `StaffAddress`.
    /// Computed as `Int64(partIndex) * 1_000 + Int64(staffIndexInPart)`.
    public let partAddressHash: Int64

    public init(
        staffIndex: Int,
        bankLSB: UInt8,
        program: UInt8,
        isDrums: Bool,
        partAddressHash: Int64,
    ) {
        self.staffIndex = staffIndex
        self.bankLSB = bankLSB
        self.program = program
        self.isDrums = isDrums
        self.partAddressHash = partAddressHash
    }

    /// Convenience factory that derives `partAddressHash` from a
    /// `StaffAddress` automatically.
    public init(
        staffIndex: Int,
        bankLSB: UInt8,
        program: UInt8,
        isDrums: Bool,
        staffAddress: StaffAddress,
    ) {
        self.init(
            staffIndex: staffIndex,
            bankLSB: bankLSB,
            program: program,
            isDrums: isDrums,
            partAddressHash: Int64(staffAddress.partIndex) * 1000
                + Int64(staffAddress.staffIndexInPart),
        )
    }
}

/// Codec for `[StaffParams]`.
///
/// Wire layout (generated by `@WireFormat` on `StaffParamsWire`):
/// ```
/// i32 count                       ← Array<T> length prefix
/// count × {
///   i32 staffIndex
///   u8  bankLSB
///   u8  program
///   u8  isDrums                   ← 0 = false, 1 = true
///   i64 partAddressHash
/// }
/// ```
public enum StaffParamsCodec {
    public static func encodeArray(_ params: [StaffParams]) -> Data {
        params.map(StaffParamsWire.init(from:)).encodeToData()
    }

    public static func decodeArray(_ data: Data) throws -> [StaffParams] {
        try [StaffParamsWire](decoding: data).map { $0.decoded() }
    }
}

@WireFormat
struct StaffParamsWire {
    var staffIndex: Int32
    var bankLSB: UInt8
    var program: UInt8
    var isDrums: Bool
    var partAddressHash: Int64

    init(from params: StaffParams) {
        staffIndex = Int32(params.staffIndex)
        bankLSB = params.bankLSB
        program = params.program
        isDrums = params.isDrums
        partAddressHash = params.partAddressHash
    }

    func decoded() -> StaffParams {
        StaffParams(
            staffIndex: Int(staffIndex),
            bankLSB: bankLSB,
            program: program,
            isDrums: isDrums,
            partAddressHash: partAddressHash,
        )
    }
}
