package io.github.jiyimeta.sheetmusic.compose.cursor

import java.nio.ByteBuffer
import java.nio.ByteOrder

/** A single highlight rectangle (mm/document coords). */
data class LoopHighlightFrame(
    val x: Double,
    val y: Double,
    val width: Double,
    val height: Double,
)

object LoopHighlightFrameCodec {
    private const val HEADER_BYTES = 4 // i32 count
    private const val RECT_BYTES = 32 // 4 × f64 (IEEE 754)

    /**
     * Decodes the wire format produced by Swift's `LoopHighlightCodec`
     * (generated by `@WireFormat` on `Rect`).
     *
     * Empty input returns `emptyList()` (no rects).
     *
     * Wire format (little-endian):
     *   i32 count
     *   count × { f64 x, f64 y, f64 width, f64 height }
     */
    fun decode(bytes: ByteArray): List<LoopHighlightFrame> {
        if (bytes.isEmpty()) return emptyList()
        require(bytes.size >= HEADER_BYTES) {
            "LoopHighlight payload too short: ${bytes.size}"
        }
        val buf = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        val count = buf.int
        require(bytes.size >= HEADER_BYTES + count * RECT_BYTES) {
            "LoopHighlight payload truncated: ${bytes.size} for count=$count"
        }
        val out = ArrayList<LoopHighlightFrame>(count)
        repeat(count) {
            val x = buf.double
            val y = buf.double
            val w = buf.double
            val h = buf.double
            out.add(LoopHighlightFrame(x, y, w, h))
        }
        return out
    }
}
