package io.github.jiyimeta.sheetmusic.compose.cursor

/** A single highlight rectangle (mm/document coords). */
data class LoopHighlightFrame(
    val x: Double,
    val y: Double,
    val width: Double,
    val height: Double,
)

object LoopHighlightFrameCodec {
    /**
     * Decodes the wire format produced by Swift's `LoopHighlightCodec.encode`
     * (`[Rect].encodeToData()`, generated by `@WireFormat` on `Rect`).
     *
     * Empty input returns `emptyList()` (no rects).
     *
     * Wirelet `@WireFormat` array layout (little-endian, protobuf-style TLV):
     * ```
     * varint  outerLen                       ← length-prefix wrapping the element stream
     * repeat (until outerLen consumed) {
     *   varint elementLen                     ← length-prefix of one Rect payload
     *   payload {                             ← elementLen bytes, tagged fields
     *     tag(1, FIXED64) f64 x
     *     tag(2, FIXED64) f64 y
     *     tag(3, FIXED64) f64 width
     *     tag(4, FIXED64) f64 height
     *   }
     * }
     * ```
     * Mirrors the generated `RectCodec` decode (one length-prefixed, tagged record per rect).
     */
    fun decode(bytes: ByteArray): List<LoopHighlightFrame> {
        if (bytes.isEmpty()) return emptyList()
        val r = Reader(bytes)
        val outerLen = r.varint().toInt()
        val outerEnd = r.pos + outerLen
        val out = ArrayList<LoopHighlightFrame>()
        while (r.pos < outerEnd) {
            val payloadLen = r.varint().toInt()
            val payloadEnd = r.pos + payloadLen
            var x = 0.0
            var y = 0.0
            var w = 0.0
            var h = 0.0
            while (r.pos < payloadEnd) {
                val raw = r.varint()
                val tag = (raw ushr 3).toInt()
                val wireType = (raw and 0x7L).toInt()
                when (tag) {
                    1 -> x = r.f64()
                    2 -> y = r.f64()
                    3 -> w = r.f64()
                    4 -> h = r.f64()
                    else -> r.skip(wireType)
                }
            }
            out.add(LoopHighlightFrame(x, y, w, h))
        }
        return out
    }

    /** Minimal little-endian + base-128 varint reader (mirrors the wirelet runtime read side). */
    private class Reader(private val data: ByteArray) {
        var pos = 0
            private set

        private fun u8(): Int = data[pos++].toInt() and 0xFF

        fun varint(): Long {
            var result = 0L
            var shift = 0
            while (true) {
                val b = u8()
                result = result or ((b.toLong() and 0x7F) shl shift)
                if (b and 0x80 == 0) break
                shift += 7
            }
            return result
        }

        fun f64(): Double {
            var bits = 0L
            for (i in 0 until 8) bits = bits or ((data[pos++].toLong() and 0xFF) shl (i * 8))
            return Double.fromBits(bits)
        }

        /** Skip an unknown TLV field (VARINT=0, FIXED64=1, LENGTH_DELIMITED=2, FIXED32=5). */
        fun skip(wireType: Int) {
            when (wireType) {
                0 -> varint()
                1 -> pos += 8
                2 -> pos += varint().toInt()
                5 -> pos += 4
            }
        }
    }
}
