import SheetMusicAudioCore
import SheetMusicCore
import SheetMusicEditWire
import SheetMusicFoundation
import SheetMusicMIDI

// Audio JNI bridge helpers. The testable logic lives in pure helpers so
// host-platform tests can call them directly. The Kotlin-facing entry
// points (generated by swift-java JExtractSwiftPlugin) live in this file
// and its `+Render` / `+Timeline` siblings as plain `public func`
// declarations.

// MARK: - AudioMidiBridge namespace

package enum AudioMidiBridge {}

// MARK: - T18: Note pitch lookup + earliest item

extension AudioMidiBridge {
    package struct PitchAndStaff: Equatable {
        package let pitch: Int
        package let staffIndex: Int

        package init(pitch: Int, staffIndex: Int) {
            self.pitch = pitch
            self.staffIndex = staffIndex
        }
    }

    package static func pitchAndStaff(score: Score, noteID: NoteID) -> PitchAndStaff? {
        guard let note = score[noteID],
              let staffIndex = score.allStaves.firstIndex(where: { $0.address == noteID.staff })
        else { return nil }
        return PitchAndStaff(pitch: note.pitch, staffIndex: staffIndex)
    }

    /// Returns `(pitch as UInt32) << 32 | (staffIndex as UInt32)`.
    /// Returns the sentinel `0xFFFFFFFFFFFFFFFF` (-1 as Int64) when
    /// the noteId no longer resolves.
    package static func pitchAndStaffOfNote(score: Score, noteId: NoteID) -> Int64 {
        let invalid = Int64(bitPattern: 0xFFFF_FFFF_FFFF_FFFF)
        guard let resolved = pitchAndStaff(score: score, noteID: noteId) else { return invalid }
        let pitch = UInt32(clamping: resolved.pitch)
        let staffIdx = UInt32(resolved.staffIndex)
        return Int64(bitPattern: (UInt64(pitch) << 32) | UInt64(staffIdx))
    }

    package static func earliestItem(score: Score, ids: [ScoreItemID]) -> ScoreItemID? {
        PlaybackTimeline(score: score).earliest(of: ids)
    }

    package static func earliestOf(score: Score, ids: [ScoreItemID]) -> Data {
        guard let earliest = earliestItem(score: score, ids: ids) else { return Data() }
        return ScoreItemIDCodec.encode(earliest)
    }
}

extension AudioMidiBridge {
    /// Looks up `id`'s end tick in the timeline. Returns -1 when the
    /// id has no entry in `itemEndTicks` (only `.note` and `.rest`
    /// items are tracked) or when the score could not be resolved by
    /// the caller side.
    package static func itemEndTick(score: Score, id: ScoreItemID) -> Int64 {
        let timeline = PlaybackTimeline(score: score)
        guard let endTick = timeline.itemEndTicks[id] else { return -1 }
        return Int64(endTick)
    }
}
