import Foundation
import SheetMusicCore
import Wirelet

/// Instrument/channel parameters for one mixer strip, passed across the
/// JNI boundary so Kotlin can build its own per-(part × instrument)
/// mixer strips — the Android mirror of the Apple `LiveChannelPlan`
/// mixer (`PlaybackEngine.rebuildMixerChannels`).
///
/// Unlike `StaffParams` (keyed on `staffIndex`, one entry per staff),
/// this is keyed on `(partIndex, ordinal)` — one entry per DEDUPED
/// (part × instrument) strip, matching `LiveChannelPlan.Strip`. A part
/// with a mid-score instrument change contributes more than one entry;
/// a grand-staff part with no change contributes exactly one.
public struct InstrumentParams: Equatable, Sendable {
    public let partIndex: Int
    /// Index into the part's DEDUPED instruments in first-appearance
    /// order — `LiveChannelPlan.Strip.ordinal`.
    public let ordinal: Int
    /// The live single-port MIDI channel (`0...15`) this strip's
    /// program / volume / mute must be routed through — NOT
    /// `staffIndex`, which only ever names the part's tick-0 channel.
    public let liveChannel: Int
    public let bankLSB: UInt8
    public let program: UInt8
    public let isDrums: Bool
    /// Mixer display label — bare part label for the primary strip,
    /// "PartLabel (InstrumentLabel)" for a secondary strip whose
    /// instrument name differs from the part's own.
    public let displayName: String
    /// Instrument channel volume (MIDI CC7, 0...127) — the initial
    /// strip volume.
    public let channelVolume: UInt8

    public init(
        partIndex: Int,
        ordinal: Int,
        liveChannel: Int,
        bankLSB: UInt8,
        program: UInt8,
        isDrums: Bool,
        displayName: String,
        channelVolume: UInt8,
    ) {
        self.partIndex = partIndex
        self.ordinal = ordinal
        self.liveChannel = liveChannel
        self.bankLSB = bankLSB
        self.program = program
        self.isDrums = isDrums
        self.displayName = displayName
        self.channelVolume = channelVolume
    }
}

/// Codec for `[InstrumentParams]`.
///
/// Wire layout (generated by `@WireFormat` on `InstrumentParamsWire`):
/// ```
/// i32 count                       ← Array<T> length prefix
/// count × {
///   i32 partIndex
///   i32 ordinal
///   i32 liveChannel
///   u8  bankLSB
///   u8  program
///   u8  isDrums                   ← 0 = false, 1 = true
///   str displayName
///   u8  channelVolume             ← MIDI CC7 (0...127)
/// }
/// ```
/// New fields are appended (tags ≥ 6) so the original tags keep their
/// numbers; the tag-based Kotlin decoder skips any it doesn't recognize.
public enum InstrumentParamsCodec {
    public static func encodeArray(_ params: [InstrumentParams]) -> Data {
        params.map(InstrumentParamsWire.init(from:)).encodeToData()
    }

    public static func decodeArray(_ data: Data) throws -> [InstrumentParams] {
        try [InstrumentParamsWire](decoding: data).map { $0.decoded() }
    }
}

@WireFormat
package struct InstrumentParamsWire {
    var partIndex: Int32
    var ordinal: Int32
    var liveChannel: Int32
    var bankLSB: UInt8
    var program: UInt8
    var isDrums: Bool
    var displayName: String
    var channelVolume: UInt8

    init(from params: InstrumentParams) {
        partIndex = Int32(params.partIndex)
        ordinal = Int32(params.ordinal)
        liveChannel = Int32(params.liveChannel)
        bankLSB = params.bankLSB
        program = params.program
        isDrums = params.isDrums
        displayName = params.displayName
        channelVolume = params.channelVolume
    }

    func decoded() -> InstrumentParams {
        InstrumentParams(
            partIndex: Int(partIndex),
            ordinal: Int(ordinal),
            liveChannel: Int(liveChannel),
            bankLSB: bankLSB,
            program: program,
            isDrums: isDrums,
            displayName: displayName,
            channelVolume: channelVolume,
        )
    }
}
