import Foundation
import SheetMusicAudioCore
import Wirelet

/// Codec for `[MetronomeBeat]`.
///
/// Wire layout (generated by `@WireFormat` on `MetronomeBeatWire`):
/// ```
/// i32 count                     ← Array<T> length prefix
/// count × {
///   i64 tick
///   u8  isDownbeat              ← 0 = upbeat, 1 = downbeat
/// }
/// ```
///
/// The mirror `MetronomeBeatWire` exists because the domain type uses
/// `tick: Int` (platform-width) — the wire is intentionally 64-bit so
/// it stays stable across ABIs.
public enum MetronomeBeatCodec {
    public static func encodeArray(_ beats: [MetronomeBeat]) -> Data {
        beats.map(MetronomeBeatWire.init(from:)).encodeToData()
    }

    public static func decodeArray(_ data: Data) throws -> [MetronomeBeat] {
        try [MetronomeBeatWire](decoding: data).map { $0.decoded() }
    }
}

@WireFormat
package struct MetronomeBeatWire {
    var tick: Int64
    var isDownbeat: Bool

    init(from beat: MetronomeBeat) {
        tick = Int64(beat.tick)
        isDownbeat = beat.isDownbeat
    }

    func decoded() -> MetronomeBeat {
        MetronomeBeat(tick: Int(tick), isDownbeat: isDownbeat)
    }
}
