import SheetMusicAudioCore
import SheetMusicFoundation
import Wirelet

/// Codec for a ``PreviewPlan`` — Swift → Kotlin direction. The Android engine asks the shared
/// ``NotePreviewPolicy`` what an audition should do and executes the answer, so only the encoder is here.
///
/// Wire layout (generated by `@WireFormat` on `PreviewPlanWire`):
/// ```
/// i64 generation
/// i32 supersedesChannel      ← -1 = nothing to silence first
/// i32 supersedesPitch        ← meaningless when supersedesChannel is -1
/// i32 channel
/// i32 pitch
/// i32 velocity
/// u8  isDrum                 ← 0 = false, 1 = true
/// i32 ringMilliseconds
/// i32 releaseTailMilliseconds
/// ```
public enum PreviewPlanCodec {
    public static func encode(_ plan: PreviewPlan) -> Data {
        PreviewPlanWire(from: plan).encodeToData()
    }
}

@WireFormat
package struct PreviewPlanWire {
    var generation: Int64
    var supersedesChannel: Int32
    var supersedesPitch: Int32
    var channel: Int32
    var pitch: Int32
    var velocity: Int32
    var isDrum: Bool
    var ringMilliseconds: Int32
    var releaseTailMilliseconds: Int32

    init(from plan: PreviewPlan) {
        generation = Int64(bitPattern: plan.generation)
        supersedesChannel = plan.supersedes.map { Int32($0.channel) } ?? -1
        supersedesPitch = plan.supersedes.map { Int32($0.pitch) } ?? 0
        channel = Int32(plan.voice.channel)
        pitch = Int32(plan.voice.pitch)
        velocity = Int32(plan.velocity)
        isDrum = plan.isDrum
        ringMilliseconds = Int32(plan.ringMilliseconds)
        releaseTailMilliseconds = Int32(plan.releaseTailMilliseconds)
    }
}

/// A ``NotePreviewPolicy`` behind a lock, for the JNI entry points.
///
/// The policy is a value type on purpose — it stays testable on the host and portable to WebAssembly — and the
/// Apple engine, being main-actor isolated, needs nothing more. Android does: `playPreview` runs on whatever
/// thread sounded the note (an editing session has its own), while the end action runs on a coroutine
/// dispatcher, so the two reach the policy concurrently. This is the smallest thing that makes that safe, and it
/// lives on the bridge side so the shared type does not carry a lock nobody else needs.
public final class NotePreviewCoordinator: @unchecked Sendable {
    private let lock = SerialLock(label: "SheetMusicBridgeCore.NotePreviewCoordinator")
    private var policy = NotePreviewPolicy()

    public init() {}

    public func begin(
        channel: UInt8,
        pitch: UInt8,
        velocity: UInt8,
        isDrum: Bool,
        ringMilliseconds: Int,
    ) -> PreviewPlan {
        lock.withLock {
            policy.begin(
                voice: PreviewVoice(channel: channel, pitch: pitch),
                velocity: velocity,
                isDrum: isDrum,
                ringMilliseconds: ringMilliseconds,
            )
        }
    }

    public func end(generation: UInt64) -> PreviewVoice? {
        lock.withLock { policy.end(generation: generation) }
    }

    public func silence() -> PreviewVoice? {
        lock.withLock { policy.silence() }
    }
}
