import Foundation
import SheetMusicAudioCore
import SheetMusicCore
import SheetMusicMIDI

// Audio JNI bridge helpers. The testable logic lives in pure helpers so
// host-platform tests can call them directly. The Kotlin-facing entry
// points (generated by swift-java JExtractSwiftPlugin) live in this file
// and its `+Render` / `+Timeline` siblings as plain `public func`
// declarations.

// MARK: - AudioMidiBridge namespace

enum AudioMidiBridge {}

// MARK: - T18: Note pitch lookup + earliest item

extension AudioMidiBridge {
    /// Returns `(pitch as UInt32) << 32 | (staffIndex as UInt32)`.
    /// Returns the sentinel `0xFFFFFFFFFFFFFFFF` (-1 as Int64) when
    /// the noteId no longer resolves.
    static func pitchAndStaffOfNote(score: Score, noteId: NoteID) -> Int64 {
        let invalid = Int64(bitPattern: 0xFFFF_FFFF_FFFF_FFFF)
        guard let staff = score[noteId.staff] else { return invalid }
        let flatIdx = score.allStaves.firstIndex {
            $0.address == noteId.staff
        } ?? -1
        guard flatIdx >= 0,
              noteId.measureIndex < staff.measures.count
        else { return invalid }
        let measure = staff.measures[noteId.measureIndex]
        guard noteId.voiceIndex < measure.voices.count else { return invalid }
        let voice = measure.voices[noteId.voiceIndex]
        guard noteId.elementIndex < voice.elements.count,
              case let .chord(chord) = voice.elements[noteId.elementIndex],
              noteId.noteIndexInChord < chord.notes.count
        else { return invalid }
        let pitch = UInt32(clamping: chord.notes[noteId.noteIndexInChord].pitch)
        let staffIdx = UInt32(flatIdx)
        return Int64(bitPattern: (UInt64(pitch) << 32) | UInt64(staffIdx))
    }

    static func earliestOf(score: Score, ids: [ScoreItemID]) -> Data {
        let timeline = PlaybackTimeline(score: score)
        guard let earliest = timeline.earliest(of: ids) else { return Data() }
        return ScoreItemIDCodec.encode(earliest)
    }
}

extension AudioMidiBridge {
    /// Looks up `id`'s end tick in the timeline. Returns -1 when the
    /// id has no entry in `itemEndTicks` (only `.note` and `.rest`
    /// items are tracked) or when the score could not be resolved by
    /// the caller side.
    static func itemEndTick(score: Score, id: ScoreItemID) -> Int64 {
        let timeline = PlaybackTimeline(score: score)
        guard let endTick = timeline.itemEndTicks[id] else { return -1 }
        return Int64(endTick)
    }
}

// MARK: - swift-java entry points

/// JNI entry point exposed via swift-java for the Kotlin
/// `SheetMusicAudioJNI.nativePitchAndStaffOfNote(...)` call site.
/// Returns the sentinel `0xFFFF_FFFF_FFFF_FFFF` (-1 as Int64) when the
/// score handle is unknown or the note id no longer resolves.
public func nativePitchAndStaffOfNote(scoreHandle: Int64, noteIdBytes: Data) -> Int64 {
    let invalid = Int64(bitPattern: 0xFFFF_FFFF_FFFF_FFFF)
    guard let score = scoreTable.value(for: scoreHandle) else { return invalid }
    guard !noteIdBytes.isEmpty else { return invalid }
    guard let noteId = try? PathIDCodecs.decode(noteIdBytes) else { return invalid }
    return AudioMidiBridge.pitchAndStaffOfNote(score: score, noteId: noteId)
}

/// JNI entry point exposed via swift-java for the Kotlin
/// `SheetMusicAudioJNI.nativeEarliestOf(...)` call site. Returns an empty
/// `Data` when the score handle is unknown, the ids payload is empty /
/// undecodable, or the timeline reports no earliest item.
public func nativeEarliestOf(scoreHandle: Int64, idsBytes: Data) -> Data {
    guard let score = scoreTable.value(for: scoreHandle) else { return Data() }
    guard !idsBytes.isEmpty,
          let ids = try? ScoreItemIDCodec.decodeArray(idsBytes)
    else { return Data() }
    return AudioMidiBridge.earliestOf(score: score, ids: ids)
}
