import SheetMusicCore
import SheetMusicFoundation
import SheetMusicXMLTools

extension KeySignature {
    /// Every direct `<KeySig>` child read by this decoder. `actualKey`
    /// is generated by the encoder from the instrument transposition,
    /// so it is consumed here as encoder-owned data as well.
    ///
    /// `concertKey`, `accidental`, and `mode` cannot be preserved: the
    /// first two collapse into one `concertKey` model value, while
    /// `mode` participates in the custom-key fallback below. The
    /// encoder then chooses the target-version spelling.
    private static let consumedKeySignatureChildren: Set = [
        "accidental", "actualKey", "color", "concertKey", "custom", "mode",
        "offset", "placement", "showCourtesySig", "visible",
    ]

    static func decode(_ node: XMLTreeNode) throws -> KeySignature {
        // Modern mscx uses <concertKey>; older forms use <accidental>.
        let concertKey: Int
        if let text = node.first("concertKey")?.text, let key = Int(text) {
            concertKey = key
        } else if let text = node.first("accidental")?.text, let key = Int(text) {
            concertKey = key
        } else if node.children.contains(where: { $0.name == "custom" || $0.name == "mode" }) {
            // Custom key signatures (<custom>1</custom>, often with <mode>none</mode>)
            // describe their accidentals via <KeySym> children rather than a fifths
            // count. Our model only stores fifths, so treat them as no sharps/flats.
            concertKey = 0
        } else {
            throw SheetMusicError.malformedScore(ScoreFault(
                code: "mscx.keySig.missingConcertKeyOrAccidental",
                message: "KeySig missing <concertKey>/<accidental>",
                location: "KeySig",
            ))
        }
        // `<showCourtesySig>` is written only when off, so an absent tag means the courtesy is drawn.
        var key = KeySignature(
            concertKey: concertKey,
            showCourtesy: (node.first("showCourtesySig")?.text ?? "1") != "0",
            preservedMarkup: node.preservedMarkup(
                consuming: consumedKeySignatureChildren,
            ),
        )
        key.elementProperties = ElementProperties(decodingMSCXChildrenOf: node)
        return key
    }
}
