import Foundation
import SheetMusicCore
import Wirelet

/// Codec for `ClefAnchor` — a sum-type variable-length payload.
///
/// Wire layout (generated by `@WireFormatChoice` on `ClefAnchorWire` — Wirelet's TLV scheme, see
/// `EditIntentCodec.swift`'s doc comment for the tag-and-varint format this describes):
/// ```
/// varint(payloadLength) + payload, where payload is varint(caseIndex) followed by the case's own encoding.
/// Case indices, matching ClefAnchor's declaration order:
/// 0 = explicit(VoiceElementIDWire), see PathIDCodecs.swift
/// 1 = staffDefault(StaffAddressWire), see StaffAddressCodec.swift
/// ```
public enum ClefAnchorCodec {
    public static func encode(_ value: ClefAnchor) -> Data {
        ClefAnchorWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> ClefAnchor {
        try ClefAnchorWire(decoding: data).decoded()
    }
}

@WireFormatChoice
public enum ClefAnchorWire {
    case explicit(VoiceElementIDWire)
    case staffDefault(StaffAddressWire)

    public init(from value: ClefAnchor) {
        switch value {
        case let .explicit(id):
            self = .explicit(VoiceElementIDWire(from: id))
        case let .staffDefault(staff):
            self = .staffDefault(StaffAddressWire(from: staff))
        }
    }

    public func decoded() -> ClefAnchor {
        switch self {
        case let .explicit(wire):
            return .explicit(wire.decoded())
        case let .staffDefault(wire):
            return .staffDefault(wire.decoded())
        }
    }
}
