import Foundation
import SheetMusicCore
import Wirelet

/// Display settings passed from the Android Reader to the layout bridge across JNI.
///
/// Wire layout (generated by `@WireFormat`):
/// - `u8 layoutMode` — 0 = vertical, 1 = horizontal, 2 = page
/// - `f64 staffSize`
/// - `u8 honorLayoutBreaks`
/// - `u8 collapseMultiMeasureRests`
/// - `u8 showsInvisibleElements`
/// - `i32 hiddenStavesCount` + `[StaffAddressWire]` × count
/// - `i32 clefOverridesCount` + `[ClefOverrideWire]` × count
@WireFormat
public struct LayoutOptionsWire {
    public var layoutMode: UInt8 // 0 = vertical, 1 = horizontal, 2 = page
    public var staffSize: Double
    public var honorLayoutBreaks: UInt8 // 0/1
    public var collapseMultiMeasureRests: UInt8 // 0/1
    public var showsInvisibleElements: UInt8 // 0/1
    public var hiddenStaves: [StaffAddressWire]
    public var clefOverrides: [ClefOverrideWire]
}

/// A clef override entry: maps a staff address to a raw clef type string (e.g. `"F8va"`).
@WireFormat
public struct ClefOverrideWire {
    public var address: StaffAddressWire
    public var rawType: String
}

extension LayoutOptionsWire {
    /// The layout mode decoded from `layoutMode`.
    public enum Mode: UInt8 { case vertical = 0, horizontal = 1, page = 2 }

    public var mode: Mode {
        Mode(rawValue: layoutMode) ?? .vertical
    }

    public var hiddenStaffAddresses: Set<StaffAddress> {
        Set(hiddenStaves.map { $0.decoded() })
    }

    public var clefOverrideMap: [StaffAddress: String] {
        Dictionary(uniqueKeysWithValues: clefOverrides.map { ($0.address.decoded(), $0.rawType) })
    }

    /// Vertical-mode options with engine defaults — no hidden staves, no clef
    /// overrides, honor authored breaks, multi-measure rests off, invisible
    /// elements hidden. Used as the fallback when a caller has no display
    /// options (legacy `LayoutBridge.compute`).
    public static var verticalDefault: LayoutOptionsWire {
        LayoutOptionsWire(
            layoutMode: Mode.vertical.rawValue,
            staffSize: 28,
            honorLayoutBreaks: 1,
            collapseMultiMeasureRests: 0,
            showsInvisibleElements: 0,
            hiddenStaves: [],
            clefOverrides: [],
        )
    }
}

/// Codec for `LayoutOptionsWire`.
public enum LayoutOptionsCodec {
    public static func decode(_ data: Data) throws -> LayoutOptionsWire {
        try LayoutOptionsWire(decoding: data)
    }
}
