package com.example.sheetmusic.cursor

import java.nio.ByteBuffer
import java.nio.ByteOrder

/** Bounding rectangle (document/mm coordinates) returned by nativeCursorFrame. */
data class CursorFrame(
    val x: Double,
    val y: Double,
    val width: Double,
    val height: Double,
) {
    companion object {
        private const val FRAME_BYTES = 32 // 4 × f64

        /**
         * Decodes the wire format produced by Swift's `CursorFrameCodec`
         * (generated by `@WireFormat` on `DecodedFrame`).
         *
         * Returns null for empty input, which signals "cursor did not resolve"
         * (e.g. stale ID after a re-layout).
         *
         * Wire format (little-endian, 32 bytes):
         *   f64 x, f64 y, f64 width, f64 height        ← IEEE 754, raw
         */
        fun decode(bytes: ByteArray): CursorFrame? {
            if (bytes.isEmpty()) return null
            require(bytes.size >= FRAME_BYTES) { "CursorFrame payload too short: ${bytes.size}" }
            val buf = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
            val x = buf.double
            val y = buf.double
            val w = buf.double
            val h = buf.double
            return CursorFrame(x, y, w, h)
        }
    }
}
