import WireFormatSchema

enum ChoiceEmitter {
    static func emit(
        _ choice: WireChoice,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        nameTransform: NameTransform,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        // Collect non-primitive referenced types (for `import` lines).
        var referenced = Set<String>()
        for c in choice.cases {
            for ty in c.payloadTypes where KotlinTypeMap.primitive(ty) == nil {
                referenced.insert(nameTransform.apply(to: ty))
            }
        }
        let extraImports = referenced.sorted()
            .map { "import \(modelPackage).\($0)" }
            .joined(separator: "\n")

        let encodeBranches = choice.cases.enumerated().map { idx, c in
            emitEncodeBranch(case: c, index: idx, kotlinName: kotlinName, nameTransform: nameTransform)
        }.joined(separator: "\n")

        let decodeBranches = choice.cases.enumerated().map { idx, c in
            emitDecodeBranch(case: c, index: idx, kotlinName: kotlinName, nameTransform: nameTransform)
        }.joined(separator: "\n")

        let content = """
        // Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
        package \(codecPackage)

        import \(modelPackage).\(kotlinName)
        \(extraImports.isEmpty ? "" : extraImports + "\n")\
        import io.github.jiyimeta.sheetmusic.audio.serialization.BinaryReader
        import io.github.jiyimeta.sheetmusic.audio.serialization.BinaryWriter

        internal object \(codecName) {
            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                encodePayload(value, w)
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
                when (value) {
        \(encodeBranches)
                }
            }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return decodePayload(r)
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
                return when (val disc = r.readU8().toInt()) {
        \(decodeBranches)
                    else -> throw IllegalArgumentException(
                        "Unknown \(kotlinName) discriminator: $disc",
                    )
                }
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }

    private static func emitEncodeBranch(
        case c: WireChoiceCase,
        index: Int,
        kotlinName: String,
        nameTransform: NameTransform,
    ) -> String {
        let subtype = "\(kotlinName).\(c.name.capitalizedFirst)"
        var lines: [String] = []
        lines.append("            is \(subtype) -> {")
        lines.append("                w.writeU8(\(index)u)")
        for (i, ty) in c.payloadTypes.enumerated() {
            let propAccess = "value.arg\(i)"
            if let primitive = KotlinTypeMap.primitive(ty) {
                lines.append("                " + primitive.write(propAccess))
            } else {
                let codecName = nameTransform.apply(to: ty) + "Codec"
                lines.append("                \(codecName).encodePayload(\(propAccess), w)")
            }
        }
        lines.append("            }")
        return lines.joined(separator: "\n")
    }

    private static func emitDecodeBranch(
        case c: WireChoiceCase,
        index: Int,
        kotlinName: String,
        nameTransform: NameTransform,
    ) -> String {
        let subtype = "\(kotlinName).\(c.name.capitalizedFirst)"
        if c.payloadTypes.isEmpty {
            return "                    \(index) -> \(subtype)"
        }
        var lines: [String] = []
        lines.append("                    \(index) -> \(subtype)(")
        for (i, ty) in c.payloadTypes.enumerated() {
            if let primitive = KotlinTypeMap.primitive(ty) {
                lines.append("                        arg\(i) = \(primitive.read),")
            } else {
                let codecName = nameTransform.apply(to: ty) + "Codec"
                lines.append("                        arg\(i) = \(codecName).decodePayload(r),")
            }
        }
        lines.append("                    )")
        return lines.joined(separator: "\n")
    }
}

extension String {
    fileprivate var capitalizedFirst: String {
        guard let first else { return self }
        return first.uppercased() + dropFirst()
    }
}
