import WireFormatSchema

enum StructEmitter {
    static func emit(
        _ wireStruct: WireStruct,
        kotlinName: String,
        modelPackage: String,
        codecPackage: String,
        nameTransform: NameTransform,
    ) -> KotlinFile {
        let codecName = "\(kotlinName)Codec"
        let path = codecPackage.replacingOccurrences(of: ".", with: "/") + "/\(codecName).kt"

        let encodeLines = wireStruct.fields.map { field in
            "        " + writeCall(for: field, transform: nameTransform)
        }.joined(separator: "\n")

        let decodeLocals = wireStruct.fields.map { field in
            "        val \(field.name) = " + readExpr(for: field, transform: nameTransform)
        }.joined(separator: "\n")

        let decodeBuild = wireStruct.fields.map { field in
            "            \(field.name) = \(field.name),"
        }.joined(separator: "\n")

        let content = """
        // Auto-generated by emit-kotlin-codecs. DO NOT EDIT.
        package \(codecPackage)

        import \(modelPackage).\(kotlinName)
        import io.github.jiyimeta.sheetmusic.audio.serialization.BinaryReader
        import io.github.jiyimeta.sheetmusic.audio.serialization.BinaryWriter

        internal object \(codecName) {
            fun encode(value: \(kotlinName)): ByteArray {
                val w = BinaryWriter()
                encodePayload(value, w)
                return w.toByteArray()
            }

            fun encodePayload(value: \(kotlinName), w: BinaryWriter) {
        \(encodeLines)
            }

            fun decode(data: ByteArray): \(kotlinName) {
                val r = BinaryReader(data)
                return decodePayload(r)
            }

            fun decodePayload(r: BinaryReader): \(kotlinName) {
        \(decodeLocals)
                return \(kotlinName)(
        \(decodeBuild)
                )
            }
        }

        """

        return KotlinFile(relativePath: path, content: content)
    }

    private static func writeCall(for field: WireField, transform: NameTransform) -> String {
        if let primitive = KotlinTypeMap.primitive(field.typeText) {
            return primitive.write("value.\(field.name)")
        }
        // Non-primitive: delegate to that type's codec by transformed name.
        let codecName = transform.apply(to: field.typeText) + "Codec"
        return "\(codecName).encodePayload(value.\(field.name), w)"
    }

    private static func readExpr(for field: WireField, transform: NameTransform) -> String {
        if let primitive = KotlinTypeMap.primitive(field.typeText) {
            return primitive.read
        }
        let codecName = transform.apply(to: field.typeText) + "Codec"
        return "\(codecName).decodePayload(r)"
    }
}
