import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { loadSheetMusic, type SheetMusic } from "../src/index.js";

/**
 * Pins the WebAssembly build against the Apple one.
 *
 * `Score.stableFingerprint` is FNV-1a with fixed constants and no per-process
 * seed, and the draw program is deterministic, so identical input must give
 * identical output on both. That equality is the whole basis for "the browser
 * engraves what the app engraves"; the expected values are generated by
 * `swift run GenWebFixtures`, never typed by hand.
 *
 * Requires `Scripts/wasm-build-web.sh` to have run.
 */
const fixturePath = (name: string) =>
  fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url));

const scoreBytes = new Uint8Array(readFileSync(fixturePath("sample.mscz")));
const expectations = JSON.parse(
  readFileSync(fixturePath("sample-expectations.json"), "utf8"),
) as {
  title: string;
  composer: string;
  partCount: number;
  staffCount: number;
  openingQuarterBpm: number;
  fingerprint: string;
  flatByteCount: number;
  flatDigest: number;
  pageCount: number;
  firstPageWidthMM: number;
  firstPageCommandCount: number;
};

/** The metrics table the browser installs, so both sides measure alike. */
const metricsBytes = new Uint8Array(
  readFileSync(fileURLToPath(new URL("../assets/bravura.smft", import.meta.url))),
);

/** FNV-1a, 32-bit — the same walk `GenWebFixtures.digest` does in Swift. */
function digest(bytes: Uint8Array): number {
  let hash = 2166136261;
  for (const byte of bytes) {
    hash ^= byte;
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

describe("wasm bridge parity with the Apple build", () => {
  let sheetMusic: SheetMusic;

  beforeAll(async () => {
    sheetMusic = await loadSheetMusic({
      bundleURL: new URL("../dist/", import.meta.url),
      platform: "node",
    });
    expect(sheetMusic.installSMuFLMetrics(metricsBytes)).toBe(true);
  });

  it("reports a non-empty engine stamp", () => {
    expect(sheetMusic.engineVersionStamp()).not.toBe("");
  });

  it("rejects an empty payload", () => {
    expect(() => sheetMusic.loadScore(new Uint8Array())).toThrow(/parse/i);
  });

  it("rejects a payload that is not a score", () => {
    expect(() => sheetMusic.loadScore(new Uint8Array([1, 2, 3, 4]))).toThrow(
      /parse/i,
    );
  });

  it("agrees on metadata", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      expect(score.metadata.title).toBe(expectations.title);
      expect(score.metadata.composer).toBe(expectations.composer);
      expect(score.metadata.partCount).toBe(expectations.partCount);
      expect(score.metadata.staffCount).toBe(expectations.staffCount);
      expect(score.metadata.openingQuarterBpm).toBeCloseTo(
        expectations.openingQuarterBpm,
        6,
      );
    } finally {
      score.release();
    }
  });

  it("agrees on the fingerprint", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      expect(score.fingerprint).toBe(expectations.fingerprint);
    } finally {
      score.release();
    }
  });

  it("agrees on the draw program byte for byte", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      const raw = score.layoutBytes({ pageWidthMM: 210, pageHeightMM: 297 });
      expect(raw.length).toBe(expectations.flatByteCount);
      expect(digest(raw)).toBe(expectations.flatDigest);
    } finally {
      score.release();
    }
  });

  it("decodes the draw program to the expected shape", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      const pages = score.layout({ pageWidthMM: 210, pageHeightMM: 297 });
      expect(pages).toHaveLength(expectations.pageCount);
      expect(pages[0]!.widthMM).toBe(expectations.firstPageWidthMM);
      expect(pages[0]!.commands).toHaveLength(
        expectations.firstPageCommandCount,
      );
    } finally {
      score.release();
    }
  });

  it("reports page boundaries after a layout", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      score.layout({ pageWidthMM: 210, pageHeightMM: 297 });
      const breaks = score.pageBreaks({ pageHeightMM: 297 });
      expect(breaks.length).toBeGreaterThanOrEqual(2);
      expect(breaks[0]).toBe(0);
      expect(breaks[breaks.length - 1]).toBeGreaterThan(0);
    } finally {
      score.release();
    }
  });

  it("reports no page boundaries before a layout", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      expect(score.pageBreaks({ pageHeightMM: 297 })).toHaveLength(0);
    } finally {
      score.release();
    }
  });

  it("a released score refuses further use", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    score.release();
    expect(() => score.metadata).toThrow(/released/i);
    expect(() => score.layoutBytes({ pageWidthMM: 210, pageHeightMM: 297 })).toThrow(
      /released/i,
    );
  });

  it("releasing twice is safe", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    score.release();
    score.release();
  });
});
