import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { beforeAll, describe, expect, it } from "vitest";
import { loadSheetMusic, splitIntoBands, type SheetMusic } from "../src/index.js";

/**
 * Pins the WebAssembly build against the Apple one.
 *
 * `Score.stableFingerprint` is FNV-1a with fixed constants and no per-process
 * seed, and the draw program is deterministic, so identical input must give
 * identical output on both. That equality is the whole basis for "the browser
 * engraves what the app engraves"; the expected values are generated by
 * `swift run GenWebFixtures`, never typed by hand.
 *
 * Requires `Scripts/wasm-build-web.sh` to have run.
 */
const fixturePath = (name: string) =>
  fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url));

const scoreBytes = new Uint8Array(readFileSync(fixturePath("sample.mscz")));
const tallScoreBytes = new Uint8Array(readFileSync(fixturePath("tall.mscz")));
const pageBreakMeasures = Array.from(
  { length: 12 },
  (_, index) => `<Measure>
        <LayoutBreak><subtype>page</subtype></LayoutBreak>
        <voice><Chord><durationType>whole</durationType><Note><pitch>${60 + (index % 8)}</pitch><tpc>14</tpc></Note></Chord></voice>
      </Measure>`,
).join("");
const pageBreakScoreBytes = new TextEncoder().encode(`<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.60">
  <Score>
    <Division>480</Division>
    <Part id="1">
      <Staff id="1"><StaffType group="pitched"><name>stdNormal</name></StaffType></Staff>
      <Instrument id="i"><longName>Piano</longName></Instrument>
    </Part>
    <Staff id="1">
      ${pageBreakMeasures}
    </Staff>
  </Score>
</museScore>`);
const inspectorScoreBytes = new TextEncoder().encode(`<?xml version="1.0" encoding="UTF-8"?>
<museScore version="4.60">
  <Score>
    <Division>480</Division>
    <Part id="1">
      <Staff id="1"><StaffType group="pitched"><name>stdNormal</name></StaffType><defaultClef>G</defaultClef></Staff>
      <Instrument id="piano"><longName>Piano</longName></Instrument>
    </Part>
    <Part id="2">
      <Staff id="2"><StaffType group="percussion"><name>perc5Line</name></StaffType><defaultClef>PERC</defaultClef></Staff>
      <Instrument id="drums"><longName>Drums</longName></Instrument>
      <show>0</show>
    </Part>
    <Staff id="1">
      <Measure>
        <voice><Chord><durationType>whole</durationType><Note><pitch>60</pitch><tpc>14</tpc></Note></Chord></voice>
      </Measure>
      <Measure>
        <voice><RehearsalMark><text>B</text></RehearsalMark><Chord><durationType>whole</durationType><Note><pitch>62</pitch><tpc>16</tpc></Note></Chord></voice>
      </Measure>
    </Staff>
    <Staff id="2">
      <Measure>
        <voice><Chord><durationType>whole</durationType><Note><pitch>36</pitch><tpc>14</tpc></Note></Chord></voice>
      </Measure>
      <Measure>
        <voice><Chord><durationType>whole</durationType><Note><pitch>38</pitch><tpc>14</tpc></Note></Chord></voice>
      </Measure>
    </Staff>
  </Score>
</museScore>`);
const expectations = JSON.parse(
  readFileSync(fixturePath("sample-expectations.json"), "utf8"),
) as {
  title: string;
  composer: string;
  partCount: number;
  staffCount: number;
  openingQuarterBpm: number;
  fingerprint: string;
  flatByteCount: number;
  flatDigest: number;
  pageCount: number;
  firstPageWidthMM: number;
  firstPageCommandCount: number;
};
const tallExpectations = JSON.parse(
  readFileSync(fixturePath("tall-expectations.json"), "utf8"),
) as {
  flatByteCount: number;
  flatDigest: number;
  pageCount: number;
  pageHeightMM: number;
  commandCount: number;
};

/** The metrics table the browser installs, so both sides measure alike. */
const metricsBytes = new Uint8Array(
  readFileSync(fileURLToPath(new URL("../assets/bravura.smft", import.meta.url))),
);
const declarationText = readFileSync(
  fileURLToPath(new URL("../dist/bridge-js.d.ts", import.meta.url)),
  "utf8",
);

/** FNV-1a, 32-bit — the same walk `GenWebFixtures.digest` does in Swift. */
function digest(bytes: Uint8Array): number {
  let hash = 2166136261;
  for (const byte of bytes) {
    hash ^= byte;
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

const defaultLayoutOptions = {
  layoutMode: 0,
  staffSize: 28,
  honorLayoutBreaks: true,
  collapseMultiMeasureRests: false,
  showsInvisibleElements: false,
  showsLyrics: true,
  transposeSemitones: 0,
  hiddenStaves: [],
  clefOverrides: [],
};

describe("wasm bridge parity with the Apple build", () => {
  let sheetMusic: SheetMusic;

  beforeAll(async () => {
    sheetMusic = await loadSheetMusic({
      bundleURL: new URL("../dist/", import.meta.url),
      platform: "node",
    });
    expect(sheetMusic.installSMuFLMetrics(metricsBytes)).toBe(true);
  });

  it("reports a non-empty engine stamp", () => {
    expect(sheetMusic.engineVersionStamp()).not.toBe("");
  });

  it("rejects an empty payload", () => {
    expect(() => sheetMusic.loadScore(new Uint8Array())).toThrow(/parse/i);
  });

  it("rejects a payload that is not a score", () => {
    expect(() => sheetMusic.loadScore(new Uint8Array([1, 2, 3, 4]))).toThrow(
      /parse/i,
    );
  });

  it("agrees on metadata", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      expect(score.metadata.title).toBe(expectations.title);
      expect(score.metadata.composer).toBe(expectations.composer);
      expect(score.metadata.partCount).toBe(expectations.partCount);
      expect(score.metadata.staffCount).toBe(expectations.staffCount);
      expect(score.metadata.openingQuarterBpm).toBeCloseTo(
        expectations.openingQuarterBpm,
        6,
      );
    } finally {
      score.release();
    }
  });

  it("agrees on the fingerprint", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      expect(score.fingerprint).toBe(expectations.fingerprint);
    } finally {
      score.release();
    }
  });

  it("agrees on the draw program byte for byte", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      const raw = score.layoutBytes({ pageWidthMM: 210, pageHeightMM: 297 });
      expect(raw.length).toBe(expectations.flatByteCount);
      expect(digest(raw)).toBe(expectations.flatDigest);
    } finally {
      score.release();
    }
  });

  it("decodes the draw program to the expected shape", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      const pages = score.layout({ pageWidthMM: 210, pageHeightMM: 297 });
      expect(pages).toHaveLength(expectations.pageCount);
      expect(pages[0]!.widthMM).toBe(expectations.firstPageWidthMM);
      expect(pages[0]!.commands).toHaveLength(
        expectations.firstPageCommandCount,
      );
    } finally {
      score.release();
    }
  });

  it("reports page boundaries after a layout", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      score.layout({ pageWidthMM: 210, pageHeightMM: 297 });
      const breaks = score.pageBreaks({ pageHeightMM: 297 });
      expect(breaks.length).toBeGreaterThanOrEqual(2);
      expect(breaks[0]).toBe(0);
      expect(breaks[breaks.length - 1]).toBeGreaterThan(0);
    } finally {
      score.release();
    }
  });

  it("uses the cached layout options for page boundaries", () => {
    const score = sheetMusic.loadScore(pageBreakScoreBytes);
    try {
      score.layout({
        pageWidthMM: 60,
        pageHeightMM: 297,
        options: { honorLayoutBreaks: false },
      });
      expect(score.pageBreaks({ pageHeightMM: 10_000 })).toHaveLength(2);

      score.layout({
        pageWidthMM: 60,
        pageHeightMM: 297,
        options: { honorLayoutBreaks: true },
      });
      expect(score.pageBreaks({ pageHeightMM: 10_000 }).length).toBeGreaterThan(2);
    } finally {
      score.release();
    }
  });

  it("reports no page boundaries before a layout", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    try {
      expect(score.pageBreaks({ pageHeightMM: 297 })).toHaveLength(0);
    } finally {
      score.release();
    }
  });

  it("reports rehearsal marks with player-second seek targets", () => {
    const score = sheetMusic.loadScore(inspectorScoreBytes);
    try {
      const marks = score.rehearsalMarks();
      expect(marks).toHaveLength(1);
      expect(marks[0]).toEqual({
        text: "B",
        measureIndex: 1,
        playerSeconds: 2,
      });
    } finally {
      score.release();
    }
  });

  it("reports flattened staff descriptors", () => {
    const score = sheetMusic.loadScore(inspectorScoreBytes);
    try {
      expect(score.staffDescriptors()).toEqual([
        {
          partIndex: 0,
          staffIndexInPart: 0,
          partName: "Piano",
          isPartVisibleInScore: true,
          defaultClefRawType: "G",
        },
        {
          partIndex: 1,
          staffIndexInPart: 0,
          partName: "Drums",
          isPartVisibleInScore: false,
          defaultClefRawType: "PERC",
        },
      ]);
    } finally {
      score.release();
    }
  });

  it("wraps measure frames as nullable objects", () => {
    const score = sheetMusic.loadScore(inspectorScoreBytes);
    try {
      expect(score.measureFrame(0)).toBeNull();
      score.layout({ pageWidthMM: 210, pageHeightMM: 297 });
      const frame = score.measureFrame(0);
      expect(frame).not.toBeNull();
      expect(frame!.widthMM).toBeGreaterThan(0);
      expect(frame!.heightMM).toBeGreaterThan(0);
      expect(score.measureFrame(999)).toBeNull();
    } finally {
      score.release();
    }
  });

  it("a released score refuses further use", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    score.release();
    expect(() => score.metadata).toThrow(/released/i);
    expect(() => score.layoutBytes({ pageWidthMM: 210, pageHeightMM: 297 })).toThrow(
      /released/i,
    );
  });

  it("releasing twice is safe", () => {
    const score = sheetMusic.loadScore(scoreBytes);
    score.release();
    score.release();
  });

  it("keeps byte blob bridge faces on Uint8Array", async () => {
    const { instantiate } = await import("../dist/instantiate.js");
    const { defaultNodeSetup } = await import("../dist/platforms/node.js");
    const { exports: bridge } = await instantiate(await defaultNodeSetup({}));
    expect(bridge.installSMuFLMetrics(metricsBytes)).toBe(true);
    const handle = bridge.loadScore(scoreBytes);
    try {
      const raw = bridge.computeLayout(handle, 210, 297, defaultLayoutOptions);
      expect(raw).toBeInstanceOf(Uint8Array);
      expect(Array.isArray(raw)).toBe(false);
    } finally {
      bridge.releaseScore(handle);
    }

    expect(declarationText).toContain("loadScore(bytes: Uint8Array): number");
    expect(declarationText).toContain("rehearsalMarkCount(handle: number): number");
    expect(declarationText).toContain(
      "measureFrame(handle: number, measureIndex: number): number[]",
    );
    expect(declarationText).toContain(
      "computeLayout(handle: number, pageWidthMM: number, pageHeightMM: number, options: LayoutOptions): Uint8Array",
    );
  });

  it("walks a bounded fraction of commands for a tall tile", () => {
    const score = sheetMusic.loadScore(tallScoreBytes);
    try {
      const raw = score.layoutBytes({ pageWidthMM: 210, pageHeightMM: 297 });
      expect(raw.length).toBe(tallExpectations.flatByteCount);
      expect(digest(raw)).toBe(tallExpectations.flatDigest);
      const page = score.layout({ pageWidthMM: 210, pageHeightMM: 297 })[0]!;
      expect(page.heightMM).toBeCloseTo(tallExpectations.pageHeightMM, 9);
      expect(page.commands).toHaveLength(tallExpectations.commandCount);

      const bands = splitIntoBands(page);
      const tile = { offsetMM: 0.4 * page.heightMM, heightMM: 100 };
      const tileBottomMM = tile.offsetMM + tile.heightMM;
      const walked = bands
        .filter(
          (band) =>
            band.topMM < tileBottomMM && band.topMM + band.heightMM > tile.offsetMM,
        )
        .reduce((sum, band) => sum + band.commands.length, 0);

      expect(bands.length).toBeGreaterThanOrEqual(4);
      expect(walked / page.commands.length).toBeLessThanOrEqual(0.6);
    } finally {
      score.release();
    }
  });
});
