// The gate that makes every OTHER test in this directory mean something.
//
// `dist/` is gitignored: the wasm the suite loads is whatever a rebuild last
// left there, and a checkout, a rebase or a branch switch moves Sources/ under
// it without touching it. Until this file existed the only thing asserted
// about the binary's identity was that `engineVersionStamp()` is not the empty
// string — and that stamp cannot detect staleness even in principle. It is an
// FNV-1a digest of `SheetMusicEngine.version`, a constant edited by hand at
// release time, so every build between two releases stamps the same number.
// `SheetMusicEngine.swift` documents that blindness in as many words. So a
// months-old binary passed the whole suite silently, and "the browser engraves
// what the app engraves" was being asserted about an engine nobody had built.
//
// The coupling has to be to CONTENT, which is what `Scripts/wasm-source-digest.sh`
// provides: one sha256 over the sources that decide the binary's behavior,
// recorded next to the binary by `Scripts/wasm-build-web.sh` at build time and
// recomputed here. One implementation of the digest, two callers — a second
// implementation in TypeScript would be one more thing that can drift.
//
// Deliberately NOT pinned to the replay fixtures: `edit-replay.json` is
// regenerated by a Swift test on the Apple side and is already content-coupled
// to the engine through its fingerprint chain. What was missing is the other
// half — that the wasm under test was built from the sources those fingerprints
// were computed from.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const repoRoot = fileURLToPath(new URL("../../../", import.meta.url));
const digestScript = fileURLToPath(
  new URL("../../../Scripts/wasm-source-digest.sh", import.meta.url),
);
const wasmPath = fileURLToPath(
  new URL("../dist/sheet-music-wasm.wasm", import.meta.url),
);
const stampPath = fileURLToPath(new URL("../dist/build-stamp.json", import.meta.url));

const rebuild = "run `npm run build:wasm` (Scripts/wasm-build-web.sh)";

interface BuildStamp {
  readonly sourceDigest?: string;
  readonly builtAt?: string;
}

function readStamp(): BuildStamp {
  if (!existsSync(stampPath)) {
    throw new Error(`${stampPath} is missing — ${rebuild}`);
  }
  return JSON.parse(readFileSync(stampPath, "utf8")) as BuildStamp;
}

function sourceDigest(): string {
  return execFileSync("bash", [digestScript, repoRoot], {
    encoding: "utf8",
  }).trim();
}

describe("the wasm under test was built from these sources", () => {
  it("has a binary at all", () => {
    expect(existsSync(wasmPath), `${wasmPath} is missing — ${rebuild}`).toBe(true);
  });

  it("carries a build stamp naming the sources it came from", () => {
    // A dist/ from before this gate existed has no stamp, and failing here is
    // the correct answer: nothing recorded what that binary was built from, so
    // it cannot be shown to be current.
    expect(
      existsSync(stampPath),
      `${stampPath} is missing — the binary predates the freshness stamp, ${rebuild}`,
    ).toBe(true);
    expect(readStamp().sourceDigest).toMatch(/^[0-9a-f]{64}$/);
  });

  it("was built from the sources in this working tree", () => {
    const recorded = readStamp().sourceDigest;
    const actual = sourceDigest();
    expect(
      actual,
      `dist/sheet-music-wasm.wasm was built from different sources ` +
        `(stamped ${recorded}, tree hashes ${actual}). Every parity assertion in ` +
        `this suite is being made against a stale engine — ${rebuild}.`,
    ).toBe(recorded);
  });
});
