package io.github.jiyimeta.sheetmusic.audio.serialization

import io.github.jiyimeta.sheetmusic.audio.model.MetronomeBeat

/**
 * Array decoder for [MetronomeBeat].
 *
 * Wire format (generated by Swift's `@WireFormat` on `MetronomeBeatWire`):
 *   i32 count + count × (tick: i64, isDownbeat: u8 0/1)
 *
 * Bytes per entry: 9 (was 16 in the v1 format with reserved padding).
 */
object MetronomeBeatDecoder {
    fun decodeArray(data: ByteArray): List<MetronomeBeat> {
        val r = BinaryReader(data)
        val count = r.readI32()
        return List(count) {
            val tick = r.readI64()
            val isDownbeat = r.readU8() != 0
            MetronomeBeat(tick = tick, isDownbeat = isDownbeat)
        }
    }
}
