package io.github.jiyimeta.sheetmusic.audio.serialization

import io.github.jiyimeta.sheetmusic.audio.model.StaffParams

/**
 * Array decoder for [StaffParams].
 *
 * Wire format (generated by Swift's `@WireFormat` on `StaffParamsWire`):
 *   i32 count + count × (staffIndex: i32, bankLSB: u8, program: u8, isDrums: u8 0/1, partAddressHash: i64)
 *
 * 15 bytes per entry (was 16 in the v1 format with reserved padding).
 */
object StaffParamsDecoder {
    fun decodeArray(data: ByteArray): List<StaffParams> {
        val r = BinaryReader(data)
        val count = r.readI32()
        return List(count) {
            val staffIndex = r.readI32()
            val bankLSB = r.readU8()
            val program = r.readU8()
            val isDrums = r.readU8() != 0
            val hash = r.readI64()
            StaffParams(
                staffIndex = staffIndex,
                bankLSB = bankLSB,
                program = program,
                isDrums = isDrums,
                partAddressHash = hash,
            )
        }
    }
}
