// Generated by GenSMuFLTables — do not edit by hand. Run: swift run GenSMuFLTables
// Codepoints are SMuFL facts from Tools/smufl/glyphnames-subset.json (glyphnames.json).
import Foundation

extension SMuFLCodepoint {
    public static let guitarVibratoStroke: UInt32 = 0xEAB2
    public static let guitarWideVibratoStroke: UInt32 = 0xEAB3
    public static let wiggleArpeggiatoDown: UInt32 = 0xEAAA
    public static let wiggleArpeggiatoDownArrow: UInt32 = 0xEAAE
    public static let wiggleArpeggiatoDownSwash: UInt32 = 0xEAAC
    public static let wiggleArpeggiatoUp: UInt32 = 0xEAA9
    public static let wiggleArpeggiatoUpArrow: UInt32 = 0xEAAD
    public static let wiggleArpeggiatoUpSwash: UInt32 = 0xEAAB
    public static let wiggleGlissando: UInt32 = 0xEAAF
    public static let wiggleGlissandoGroup1: UInt32 = 0xEABD
    public static let wiggleGlissandoGroup2: UInt32 = 0xEABE
    public static let wiggleGlissandoGroup3: UInt32 = 0xEABF
    public static let wiggleSawtooth: UInt32 = 0xEABB
    public static let wiggleSawtoothNarrow: UInt32 = 0xEABA
    public static let wiggleSawtoothWide: UInt32 = 0xEABC
    public static let wiggleSquareWave: UInt32 = 0xEAB8
    public static let wiggleSquareWaveNarrow: UInt32 = 0xEAB7
    public static let wiggleSquareWaveWide: UInt32 = 0xEAB9
    public static let wiggleTrill: UInt32 = 0xEAA4
    public static let wiggleTrillFast: UInt32 = 0xEAA3
    public static let wiggleTrillFaster: UInt32 = 0xEAA2
    public static let wiggleTrillFasterStill: UInt32 = 0xEAA1
    public static let wiggleTrillFastest: UInt32 = 0xEAA0
    public static let wiggleTrillSlow: UInt32 = 0xEAA5
    public static let wiggleTrillSlower: UInt32 = 0xEAA6
    public static let wiggleTrillSlowerStill: UInt32 = 0xEAA7
    public static let wiggleTrillSlowest: UInt32 = 0xEAA8
    public static let wiggleVibrato: UInt32 = 0xEAB0
    public static let wiggleVibratoWide: UInt32 = 0xEAB1
    public static let wiggleWavy: UInt32 = 0xEAB5
    public static let wiggleWavyNarrow: UInt32 = 0xEAB4
    public static let wiggleWavyWide: UInt32 = 0xEAB6
}
