import SheetMusicCore
import SheetMusicFoundation
import Wirelet

/// Codecs for path-based identity types: `VoiceElementID`, `NoteID`,
/// `RestID`, and `TupletID`. Wire layouts are generated by `@WireFormat`
/// on the per-type `*Wire` mirror structs — Wirelet's TLV scheme, see
/// `EditIntentCodec.swift`'s doc comment for the tag-and-varint format
/// these describe.
///
/// ```
/// VoiceElementIDWire
///   tag 1: staff         StaffAddressWire, see StaffAddressCodec.swift
///   tag 2: measureIndex  i32, zig-zag varint
///   tag 3: voiceIndex    i32, zig-zag varint
///   tag 4: elementIndex  i32, zig-zag varint
///   tag 5: reserved for SP0's optional stable identity; do not assign it
///
/// NoteIDWire
///   tag 1: staff             StaffAddressWire, see StaffAddressCodec.swift
///   tag 2: measureIndex      i32, zig-zag varint
///   tag 3: voiceIndex        i32, zig-zag varint
///   tag 4: elementIndex      i32, zig-zag varint
///   tag 5: noteIndexInChord  i32, zig-zag varint
///   tag 6: reserved for SP0's optional stable identity; do not assign it
///
/// RestIDWire
///   tag 1: staff         StaffAddressWire, see StaffAddressCodec.swift
///   tag 2: measureIndex  i32, zig-zag varint
///   tag 3: voiceIndex    i32, zig-zag varint
///   tag 4: elementIndex  i32, zig-zag varint
///   tag 5: reserved for SP0's optional stable identity; do not assign it
///
/// TupletIDWire
///   tag 1: staff              StaffAddressWire, see StaffAddressCodec.swift
///   tag 2: measureIndex       i32, zig-zag varint
///   tag 3: voiceIndex         i32, zig-zag varint
///   tag 4: startElementIndex  i32, zig-zag varint
///   tag 5: reserved for SP0's optional stable identity; do not assign it
/// ```
///
/// Top-level `NoteID` blob: `varint(payloadLength)` + `NoteIDWire` payload.
public enum PathIDCodecs {
    public static func encode(_ value: NoteID) -> Data {
        NoteIDWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> NoteID {
        try NoteIDWire(decoding: data).decoded()
    }
}

// MARK: - VoiceElementID

@WireFormat
public struct VoiceElementIDWire {
    public var staff: StaffAddressWire
    public var measureIndex: Int32
    public var voiceIndex: Int32
    public var elementIndex: Int32

    public init(from value: VoiceElementID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        elementIndex = Int32(value.elementIndex)
    }

    public func decoded() -> VoiceElementID {
        VoiceElementID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            elementIndex: Int(elementIndex),
        )
    }
}

// MARK: - NoteID

@WireFormat
public struct NoteIDWire {
    public var staff: StaffAddressWire
    public var measureIndex: Int32
    public var voiceIndex: Int32
    public var elementIndex: Int32
    public var noteIndexInChord: Int32

    public init(from value: NoteID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        elementIndex = Int32(value.elementIndex)
        noteIndexInChord = Int32(value.noteIndexInChord)
    }

    public func decoded() -> NoteID {
        NoteID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            elementIndex: Int(elementIndex),
            noteIndexInChord: Int(noteIndexInChord),
        )
    }
}

// MARK: - RestID

@WireFormat
public struct RestIDWire {
    public var staff: StaffAddressWire
    public var measureIndex: Int32
    public var voiceIndex: Int32
    public var elementIndex: Int32

    public init(from value: RestID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        elementIndex = Int32(value.elementIndex)
    }

    public func decoded() -> RestID {
        RestID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            elementIndex: Int(elementIndex),
        )
    }
}

// MARK: - TupletID

@WireFormat
public struct TupletIDWire {
    public var staff: StaffAddressWire
    public var measureIndex: Int32
    public var voiceIndex: Int32
    public var startElementIndex: Int32

    public init(from value: TupletID) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
        startElementIndex = Int32(value.startElementIndex)
    }

    public func decoded() -> TupletID {
        TupletID(
            staff: staff.decoded(),
            measureIndex: Int(measureIndex),
            voiceIndex: Int(voiceIndex),
            startElementIndex: Int(startElementIndex),
        )
    }
}
