import SheetMusicCore
import SheetMusicFoundation
import Wirelet

/// Codecs for the reference family added by the edit-command parity project (spec 2026-09-02 §2): `MeasureRef`,
/// `PartRef`, `VoiceRef`, `VoiceElementRange`. Wire layouts are generated by `@WireFormat` on the `*Wire` mirrors —
/// Wirelet's TLV scheme, see `EditIntentCodec.swift`'s doc comment for the tag-and-varint format.
///
/// Every mirror here is a NESTED struct even when it holds one integer. That nesting is the seam a future stable
/// identity lands in: Wirelet appends an `Optional` field to a struct with zero byte movement, but can never turn
/// a bare scalar into a struct compatibly. Each mirror's next unassigned tag is reserved for that field.
///
/// ```
/// MeasureRefWire
///   tag 1: measureIndex  i32, zig-zag varint
///   tag 2: reserved for SP0's optional stable identity; do not assign it
///
/// PartRefWire
///   tag 1: partIndex  i32, zig-zag varint
///   tag 2: reserved for SP0's optional stable identity; do not assign it
///
/// VoiceRefWire
///   tag 1: staff         StaffAddressWire, see StaffAddressCodec.swift
///   tag 2: measureIndex  i32, zig-zag varint
///   tag 3: voiceIndex    i32, zig-zag varint
///   tag 4: reserved for SP0's optional stable identity; do not assign it
///
/// VoiceElementRangeWire
///   tag 1: start  VoiceElementIDWire, see PathIDCodecs.swift
///   tag 2: end    VoiceElementIDWire, see PathIDCodecs.swift
///   tag 3: reserved for SP0's optional stable identity; do not assign it
/// ```
public enum ReferenceCodecs {
    public static func encode(_ value: MeasureRef) -> Data {
        MeasureRefWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> MeasureRef {
        try MeasureRefWire(decoding: data).decoded()
    }

    public static func encode(_ value: PartRef) -> Data {
        PartRefWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> PartRef {
        try PartRefWire(decoding: data).decoded()
    }

    public static func encode(_ value: VoiceRef) -> Data {
        VoiceRefWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> VoiceRef {
        try VoiceRefWire(decoding: data).decoded()
    }

    public static func encode(_ value: VoiceElementRange) -> Data {
        VoiceElementRangeWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> VoiceElementRange {
        try VoiceElementRangeWire(decoding: data).decoded()
    }
}

@WireFormat
public struct MeasureRefWire {
    public var measureIndex: Int32

    public init(from value: MeasureRef) {
        measureIndex = Int32(value.measureIndex)
    }

    public func decoded() -> MeasureRef {
        MeasureRef(measureIndex: Int(measureIndex))
    }
}

@WireFormat
public struct PartRefWire {
    public var partIndex: Int32

    public init(from value: PartRef) {
        partIndex = Int32(value.partIndex)
    }

    public func decoded() -> PartRef {
        PartRef(partIndex: Int(partIndex))
    }
}

@WireFormat
public struct VoiceRefWire {
    public var staff: StaffAddressWire
    public var measureIndex: Int32
    public var voiceIndex: Int32

    public init(from value: VoiceRef) {
        staff = StaffAddressWire(from: value.staff)
        measureIndex = Int32(value.measureIndex)
        voiceIndex = Int32(value.voiceIndex)
    }

    public func decoded() -> VoiceRef {
        VoiceRef(staff: staff.decoded(), measureIndex: Int(measureIndex), voiceIndex: Int(voiceIndex))
    }
}

@WireFormat
public struct VoiceElementRangeWire {
    public var start: VoiceElementIDWire
    public var end: VoiceElementIDWire

    public init(from value: VoiceElementRange) {
        start = VoiceElementIDWire(from: value.start)
        end = VoiceElementIDWire(from: value.end)
    }

    public func decoded() -> VoiceElementRange {
        VoiceElementRange(start: start.decoded(), end: end.decoded())
    }
}
