import Foundation
import SheetMusicCore
import Wirelet

/// Codec for `ScoreItemID` — a sum-type variable-length payload, plus
/// top-level single + array blobs.
///
/// Wire layout (generated by `@WireFormatChoice` on `ScoreItemIDWire` — Wirelet's TLV scheme, see
/// `EditIntentCodec.swift`'s doc comment for the tag-and-varint format this describes):
/// ```
/// varint(payloadLength) + payload, where payload is varint(caseIndex) followed by the case's own encoding.
/// Case indices, matching ScoreItemID's declaration order:
/// 0 = note(NoteIDWire), see PathIDCodecs.swift
/// 1 = rest(RestIDWire), see PathIDCodecs.swift
/// 2 = tuplet(TupletIDWire), see PathIDCodecs.swift
/// 3 = clef(ClefAnchorWire), see ClefAnchorCodec.swift
/// ```
///
/// Top-level single: `ScoreItemIDWire` bytes directly. Array: via `Array<T: WireFormat>`'s own encoding
/// (`varint(count)` + each element's length-delimited encoding).
public enum ScoreItemIDCodec {
    public static func encode(_ value: ScoreItemID) -> Data {
        ScoreItemIDWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> ScoreItemID {
        try ScoreItemIDWire(decoding: data).decoded()
    }

    public static func encodeArray(_ values: [ScoreItemID]) -> Data {
        values.map(ScoreItemIDWire.init(from:)).encodeToData()
    }

    public static func decodeArray(_ data: Data) throws -> [ScoreItemID] {
        try [ScoreItemIDWire](decoding: data).map { $0.decoded() }
    }
}

@WireFormatChoice
public enum ScoreItemIDWire {
    case note(NoteIDWire)
    case rest(RestIDWire)
    case tuplet(TupletIDWire)
    case clef(ClefAnchorWire)

    public init(from value: ScoreItemID) {
        switch value {
        case let .note(id):
            self = .note(NoteIDWire(from: id))
        case let .rest(id):
            self = .rest(RestIDWire(from: id))
        case let .tuplet(id):
            self = .tuplet(TupletIDWire(from: id))
        case let .clef(anchor):
            self = .clef(ClefAnchorWire(from: anchor))
        }
    }

    public func decoded() -> ScoreItemID {
        switch self {
        case let .note(wire): return .note(wire.decoded())
        case let .rest(wire): return .rest(wire.decoded())
        case let .tuplet(wire): return .tuplet(wire.decoded())
        case let .clef(wire): return .clef(wire.decoded())
        }
    }
}
