import SheetMusicCore
import SheetMusicFoundation
import Wirelet

/// Codec for `ScoreItemID` — a sum-type variable-length payload, plus
/// top-level single + array blobs.
///
/// Wire layout (generated by `@WireFormatChoice` on `ScoreItemIDWire` — Wirelet's TLV scheme, see
/// `EditIntentCodec.swift`'s doc comment for the tag-and-varint format this describes):
/// ```
/// varint(payloadLength) + payload, where payload is varint(caseIndex) followed by the case's own encoding.
/// Case indices, matching ScoreItemID's declaration order:
/// 0 = note(NoteIDWire), see PathIDCodecs.swift
/// 1 = rest(RestIDWire), see PathIDCodecs.swift
/// 2 = tuplet(TupletIDWire), see PathIDCodecs.swift
/// 3 = clef(ClefAnchorWire), see ClefAnchorCodec.swift
/// 4 = text(ScoreTextIDWire), below
/// 5 = element(ScoreElementIDWire), below
///
/// ScoreTextIDWire — case indices matching ScoreTextID's declaration order:
/// 0 = lyric(LyricTextIDWire)
///       tag 1: anchor  VoiceElementIDWire, see PathIDCodecs.swift
///       tag 2: verse   i32, zig-zag varint
/// 1 = staffText(StaffTextIDWire)
///       tag 1: anchor        VoiceElementIDWire, see PathIDCodecs.swift
///       tag 2: isSystemText  bool, varint
/// 2 = harmony(VoiceElementIDWire), see PathIDCodecs.swift
/// 3 = rehearsalMark(i32 measureIndex, zig-zag varint)
/// ```
///
/// **`staffText`'s style crosses as a Bool, not as a `TextStyleType`**, matching
/// `SetStaffTextIntentWire.isSystemText` — the same style distinction the command that edits the text
/// takes. That is lossless for every value this case can hold: `ScoreHitTester`'s `textTarget` reports a
/// `.staffText` target only for `.staffText` and `.systemText` (an `.instrumentChange` shares the layout
/// case but has no text-entry command and is excluded there).
///
/// Top-level single: `ScoreItemIDWire` bytes directly. Array: via `Array<T: WireFormat>`'s own encoding
/// (`varint(count)` + each element's length-delimited encoding).
public enum ScoreItemIDCodec {
    public static func encode(_ value: ScoreItemID) -> Data {
        ScoreItemIDWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> ScoreItemID {
        try ScoreItemIDWire(decoding: data).decoded()
    }

    public static func encodeArray(_ values: [ScoreItemID]) -> Data {
        values.map(ScoreItemIDWire.init(from:)).encodeToData()
    }

    public static func decodeArray(_ data: Data) throws -> [ScoreItemID] {
        try [ScoreItemIDWire](decoding: data).map { try $0.decoded() }
    }
}

@WireFormatChoice
public enum ScoreItemIDWire {
    case note(NoteIDWire)
    case rest(RestIDWire)
    case tuplet(TupletIDWire)
    case clef(ClefAnchorWire)
    case text(ScoreTextIDWire)
    case element(ScoreElementIDWire)

    public init(from value: ScoreItemID) {
        switch value {
        case let .note(id):
            self = .note(NoteIDWire(from: id))
        case let .rest(id):
            self = .rest(RestIDWire(from: id))
        case let .tuplet(id):
            self = .tuplet(TupletIDWire(from: id))
        case let .clef(anchor):
            self = .clef(ClefAnchorWire(from: anchor))
        case let .text(id):
            self = .text(ScoreTextIDWire(from: id))
        case let .element(id):
            self = .element(ScoreElementIDWire(from: id))
        }
    }

    public func decoded() throws -> ScoreItemID {
        switch self {
        case let .note(wire): return .note(wire.decoded())
        case let .rest(wire): return .rest(wire.decoded())
        case let .tuplet(wire): return .tuplet(wire.decoded())
        case let .clef(wire): return .clef(wire.decoded())
        case let .text(wire): return .text(wire.decoded())
        case let .element(wire): return try .element(wire.decoded())
        }
    }
}

// MARK: - ScoreTextID

@WireFormat
public struct LyricTextIDWire {
    public var anchor: VoiceElementIDWire
    public var verse: Int32

    public init(anchor: VoiceElementID, verse: Int) {
        self.anchor = VoiceElementIDWire(from: anchor)
        self.verse = Int32(verse)
    }
}

@WireFormat
public struct StaffTextIDWire {
    public var anchor: VoiceElementIDWire
    public var isSystemText: Bool

    public init(anchor: VoiceElementID, style: TextStyleType) {
        self.anchor = VoiceElementIDWire(from: anchor)
        isSystemText = style == .systemText
    }
}

@WireFormatChoice
public enum ScoreTextIDWire {
    case lyric(LyricTextIDWire)
    case staffText(StaffTextIDWire)
    case harmony(VoiceElementIDWire)
    case rehearsalMark(Int32)

    public init(from value: ScoreTextID) {
        switch value {
        case let .lyric(anchor, verse):
            self = .lyric(LyricTextIDWire(anchor: anchor, verse: verse))
        case let .staffText(anchor, style):
            self = .staffText(StaffTextIDWire(anchor: anchor, style: style))
        case let .harmony(anchor):
            self = .harmony(VoiceElementIDWire(from: anchor))
        case let .rehearsalMark(measureIndex):
            self = .rehearsalMark(Int32(measureIndex))
        }
    }

    public func decoded() -> ScoreTextID {
        switch self {
        case let .lyric(wire):
            return .lyric(anchor: wire.anchor.decoded(), verse: Int(wire.verse))
        case let .staffText(wire):
            return .staffText(
                anchor: wire.anchor.decoded(),
                style: wire.isSystemText ? .systemText : .staffText,
            )
        case let .harmony(wire):
            return .harmony(anchor: wire.decoded())
        case let .rehearsalMark(measureIndex):
            return .rehearsalMark(measureIndex: Int(measureIndex))
        }
    }
}

// MARK: - ScoreElementID

/// Wire projection of the element identity. Case order is persistent; append new cases at the end.
/// Anchored and bar-addressed cases carry their own payload, so no stored Optional is needed.
@WireFormatChoice
public enum ScoreElementIDWire {
    case dynamic(VoiceElementIDWire)
    case fermata(VoiceElementIDWire)
    case breath(VoiceElementIDWire)
    case tempo(VoiceElementIDWire)
    /// Uses `Spanner.Kind.rawValue`, matching `RemoveSpannerIntentWire`; this codec does not own its case order.
    case spanner(anchor: VoiceElementIDWire, kind: String)
    case keySignature(Int32)
    case timeSignature(Int32)
    case barLine(measureIndex: Int32, role: BarLineRoleWire)
    case articulation(anchor: VoiceElementIDWire, kind: ScoreArticulationKindWire)

    public init(from value: ScoreElementID) {
        switch value {
        case let .dynamic(anchor): self = .dynamic(VoiceElementIDWire(from: anchor))
        case let .fermata(anchor): self = .fermata(VoiceElementIDWire(from: anchor))
        case let .breath(anchor): self = .breath(VoiceElementIDWire(from: anchor))
        case let .tempo(anchor): self = .tempo(VoiceElementIDWire(from: anchor))
        case let .spanner(anchor, kind):
            self = .spanner(anchor: VoiceElementIDWire(from: anchor), kind: kind.rawValue)
        case let .keySignature(index): self = .keySignature(Int32(index))
        case let .timeSignature(index): self = .timeSignature(Int32(index))
        case let .barLine(index, role):
            self = .barLine(measureIndex: Int32(index), role: BarLineRoleWire(from: role))
        case let .articulation(anchor, kind):
            self = .articulation(anchor: VoiceElementIDWire(from: anchor), kind: ScoreArticulationKindWire(from: kind))
        }
    }

    public func decoded() throws -> ScoreElementID {
        switch self {
        case let .dynamic(anchor): return .dynamic(anchor: anchor.decoded())
        case let .fermata(anchor): return .fermata(anchor: anchor.decoded())
        case let .breath(anchor): return .breath(anchor: anchor.decoded())
        case let .tempo(anchor): return .tempo(anchor: anchor.decoded())
        case let .spanner(anchor, kind):
            guard let decodedKind = Spanner.Kind(rawValue: kind) else {
                throw WireFormatError.unknownChoiceDiscriminator(0)
            }
            return .spanner(anchor: anchor.decoded(), kind: decodedKind)
        case let .keySignature(index): return .keySignature(measureIndex: Int(index))
        case let .timeSignature(index): return .timeSignature(measureIndex: Int(index))
        case let .barLine(index, role): return .barLine(measureIndex: Int(index), role: role.decoded())
        case let .articulation(anchor, kind): return .articulation(anchor: anchor.decoded(), kind: kind.decoded())
        }
    }
}

/// A closed wire choice whose declaration order is persistent; append new cases at the end.
@WireFormatChoice
public enum BarLineRoleWire {
    case explicit
    case startRepeat
    case trailing

    public init(from value: BarLineRole) {
        switch value {
        case .explicit: self = .explicit
        case .startRepeat: self = .startRepeat
        case .trailing: self = .trailing
        }
    }

    public func decoded() -> BarLineRole {
        switch self {
        case .explicit: return .explicit
        case .startRepeat: return .startRepeat
        case .trailing: return .trailing
        }
    }
}

/// A closed wire choice whose declaration order is persistent; append new cases at the end.
/// Unknown subtype strings stay distinct from modeled kinds, even when their tokens coincide.
@WireFormatChoice
public enum ScoreArticulationKindWire {
    case staccato
    case staccatissimo
    case tenuto
    case accent
    case marcato
    case accentStaccato
    case marcatoStaccato
    case unknown(String)

    public init(from value: ChordArticulation.Kind) {
        switch value {
        case .staccato: self = .staccato
        case .staccatissimo: self = .staccatissimo
        case .tenuto: self = .tenuto
        case .accent: self = .accent
        case .marcato: self = .marcato
        case .accentStaccato: self = .accentStaccato
        case .marcatoStaccato: self = .marcatoStaccato
        case let .unknown(subtype): self = .unknown(subtype)
        }
    }

    public func decoded() -> ChordArticulation.Kind {
        switch self {
        case .staccato: return .staccato
        case .staccatissimo: return .staccatissimo
        case .tenuto: return .tenuto
        case .accent: return .accent
        case .marcato: return .marcato
        case .accentStaccato: return .accentStaccato
        case .marcatoStaccato: return .marcatoStaccato
        case let .unknown(subtype): return .unknown(subtype: subtype)
        }
    }
}
