import SheetMusicCore
import SheetMusicFoundation
import Wirelet

/// Codec for `StaffAddress`.
///
/// Wire layout (generated by `@WireFormat` on `StaffAddressWire` — Wirelet's TLV scheme, see
/// `EditIntentCodec.swift`'s doc comment for the tag-and-varint format this describes):
/// ```
/// tag 1: partIndex          i32, zig-zag varint
/// tag 2: staffIndexInPart   i32, zig-zag varint
/// ```
public enum StaffAddressCodec {
    public static func encode(_ value: StaffAddress) -> Data {
        StaffAddressWire(from: value).encodeToData()
    }

    public static func decode(_ data: Data) throws -> StaffAddress {
        try StaffAddressWire(decoding: data).decoded()
    }
}

@WireFormat
public struct StaffAddressWire {
    public var partIndex: Int32
    public var staffIndexInPart: Int32

    public init(from value: StaffAddress) {
        partIndex = Int32(value.partIndex)
        staffIndexInPart = Int32(value.staffIndexInPart)
    }

    public func decoded() -> StaffAddress {
        StaffAddress(
            partIndex: Int(partIndex),
            staffIndexInPart: Int(staffIndexInPart),
        )
    }
}
