package io.github.jiyimeta.sheetmusic

import org.swift.swiftkit.core.SwiftMemoryManagement
import io.github.jiyimeta.sheetmusic.swiftjava.Data as SwiftData
import io.github.jiyimeta.sheetmusic.swiftjava.SheetMusicAndroidJNI as SwiftJavaJNI

/**
 * Thin façade over the JNI entry points generated by swift-java's
 * JExtractSwiftPlugin from `Sources/SheetMusicAndroidJNI/`.
 *
 * `libSheetMusicAndroidJNI.so` and its dependencies (libSwiftJava.so,
 * the Swift runtime) are loaded via the generated swift-java
 * [SheetMusicAndroidJNI]'s static initializer the first time any
 * delegating call below resolves the class.
 */
object SheetMusicJNI {

    /** Returns 0 on parse failure. */
    fun nativeLoadScore(bytes: ByteArray): Long {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadScore(SwiftData.fromByteArray(bytes, arena))
    }

    fun nativeReleaseScore(handle: Long) {
        SwiftJavaJNI.nativeReleaseScore(handle)
    }

    /**
     * Length-prefixed UTF-8 blob holding `(workTitle, composer)` from the
     * score's metaTags. Wire format:
     * `[titleLen:I32 LE][titleBytes][composerLen:I32 LE][composerBytes]`.
     * Missing tags come back as zero-length strings; an unknown handle
     * returns an empty array. Decode via [ScoreMetadata.decode].
     */
    fun nativeScoreMetadata(handle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeScoreMetadata(handle, arena).toByteArray()
    }

    /**
     * Quarter-note BPM of the score's opening tempo marking (the tempo governing
     * the start), or MuseScore's 120 default. The Reader multiplies this by the
     * playback rate for the inspector's "♩ = N" tempo readout.
     */
    fun nativeOpeningQuarterBpm(scoreHandle: Long): Double =
        SwiftJavaJNI.nativeOpeningQuarterBpm(scoreHandle)

    /**
     * Returns an empty array on failure (e.g. invalid handle or an
     * `optionsBlob` that fails to decode). `optionsBlob` is a
     * `LayoutOptionsWire` payload carrying the layout mode, staff size,
     * break / multi-measure-rest / invisible-element toggles, hidden staves,
     * and clef overrides from the Reader's display inspector.
     */
    fun nativeComputeLayout(
        scoreHandle: Long,
        pageWidthMM: Double,
        pageHeightMM: Double,
        optionsBlob: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeComputeLayout(
            scoreHandle,
            pageWidthMM,
            pageHeightMM,
            SwiftData.fromByteArray(optionsBlob, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Install a SMuFL glyph-metrics table on the Swift side. Returns
     * `true` on success, `false` if the byte format is invalid. Wire
     * format spec is on `Sources/SheetMusicAndroidJNI/SMuFLMetricsTable.swift`.
     */
    fun nativeInstallSMuFLMetrics(bytes: ByteArray): Boolean {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeInstallSMuFLMetrics(SwiftData.fromByteArray(bytes, arena))
    }

    /**
     * Parts/staves descriptor for the Reader display inspector's Parts section:
     * per part a name + each staff's default clef rawType. Empty array for an
     * unknown handle. Decode via the generated PartsStavesWireCodec.
     */
    fun nativePartsStaves(handle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePartsStaves(handle, arena).toByteArray()
    }

    /**
     * Resolve the bounding rectangle (document/mm coordinates) of the cursor
     * identified by [cursorBytes] within the laid-out score [scoreHandle].
     *
     * Returns a 34-byte payload in the CursorFrame wire format on success, or
     * an empty array if the cursor did not resolve (e.g. stale ID after
     * re-layout). Wire format: u16 version (=1), then 4 × i64 micros
     * (x, y, width, height), little-endian.
     */
    fun nativeCursorFrame(
        scoreHandle: Long,
        cursorBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeCursorFrame(
            scoreHandle,
            SwiftData.fromByteArray(cursorBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Bounding rectangle (document/mm coordinates) of the MEASURE the cursor
     * [cursorBytes] sits in — the measure anchor for the horizontal Reader's
     * leading-edge auto-scroll. Same wire format as [nativeCursorFrame]
     * (a single CursorFrame DecodedFrame). Empty array if unresolved.
     */
    fun nativeMeasureFrame(
        scoreHandle: Long,
        cursorBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeMeasureFrame(
            scoreHandle,
            SwiftData.fromByteArray(cursorBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve the nearest playable cursor (a chord onset or a rest) for a tap
     * at ([tapXmm], [tapYmm]) in document/mm coordinates within the laid-out
     * score [scoreHandle]. The hit-test picks the staff closest to the touch,
     * then the nearest event on it, and re-addresses the result against the full
     * (unfiltered) score so the returned cursor drives the audio engine.
     *
     * [hiddenStavesBytes] is the SAME `LayoutOptionsWire` blob passed to
     * [nativeComputeLayout] (only its hidden-staves set is read); reusing it
     * keeps the re-addressing in lockstep with the filtered layout.
     *
     * Returns a `ScoreCursor` wire payload (the format [nativeCursorFrame] /
     * [nativeMeasureFrame] accept back) on a hit, or an empty array when the
     * handle is unknown, the layout is not cached, the options blob fails to
     * decode, or the tap hit no playable element.
     */
    fun nativeNearestCursor(
        scoreHandle: Long,
        tapXmm: Double,
        tapYmm: Double,
        hiddenStavesBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeNearestCursor(
            scoreHandle,
            tapXmm,
            tapYmm,
            SwiftData.fromByteArray(hiddenStavesBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve the highlight rectangles (mm coordinates) covering a
     * loop region spanning ticks `[fromTick, toTick)`. Returns one
     * rect per intersected system; the rect spans the full staff
     * height of that system and the X range of the included measures.
     *
     * Wire format: u16 version=1, i32 count, count × 4×i64 micros.
     * Empty array when the range yields no measures.
     */
    fun nativeLoopHighlightRects(
        scoreHandle: Long,
        fromTick: Long,
        toTick: Long,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoopHighlightRects(
            scoreHandle,
            fromTick,
            toTick,
            arena,
        ).toByteArray()
    }

    /**
     * Page-break offsets (document-Y, mm) for the cached layout of [scoreHandle], paginated
     * with the same [pageHeightMM] and [optionsBytes] passed to [nativeComputeLayout] so
     * they line up with the `.page` program pages. Wire: i32 count then count × f64, big-endian.
     * `[0, top1, …, contentBottom]`; empty if the handle is unknown.
     */
    fun nativePageBreaks(scoreHandle: Long, pageHeightMM: Double, optionsBytes: ByteArray): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePageBreaks(
            scoreHandle,
            pageHeightMM,
            SwiftData.fromByteArray(optionsBytes, arena),
            arena,
        ).toByteArray()
    }
}
