package io.github.jiyimeta.sheetmusic

import org.swift.swiftkit.core.SwiftMemoryManagement
import io.github.jiyimeta.sheetmusic.swiftjava.Data as SwiftData
import io.github.jiyimeta.sheetmusic.swiftjava.SheetMusicAndroidJNI as SwiftJavaJNI

/**
 * Thin façade over the JNI entry points generated by swift-java's
 * JExtractSwiftPlugin from `Sources/SheetMusicAndroidJNI/`.
 *
 * `libSheetMusicAndroidJNI.so` and its dependencies (libSwiftJava.so,
 * the Swift runtime) are loaded via the generated swift-java
 * [SheetMusicAndroidJNI]'s static initializer the first time any
 * delegating call below resolves the class.
 */
object SheetMusicJNI {

    /** Returns 0 on parse failure. */
    fun nativeLoadScore(bytes: ByteArray): Long {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadScore(SwiftData.fromByteArray(bytes, arena))
    }

    fun nativeReleaseScore(handle: Long) {
        SwiftJavaJNI.nativeReleaseScore(handle)
    }

    /**
     * Length-prefixed UTF-8 blob holding `(workTitle, composer)` from the
     * score's metaTags. Wire format:
     * `[titleLen:I32 LE][titleBytes][composerLen:I32 LE][composerBytes]`.
     * Missing tags come back as zero-length strings; an unknown handle
     * returns an empty array. Decode via [ScoreMetadata.decode].
     */
    fun nativeScoreMetadata(handle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeScoreMetadata(handle, arena).toByteArray()
    }

    /** Returns an empty array on failure (e.g. invalid handle). */
    fun nativeComputeLayout(
        scoreHandle: Long,
        pageWidthMM: Double,
        pageHeightMM: Double,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeComputeLayout(
            scoreHandle,
            pageWidthMM,
            pageHeightMM,
            arena,
        ).toByteArray()
    }

    /**
     * Install a SMuFL glyph-metrics table on the Swift side. Returns
     * `true` on success, `false` if the byte format is invalid. Wire
     * format spec is on `Sources/SheetMusicAndroidJNI/SMuFLMetricsTable.swift`.
     */
    fun nativeInstallSMuFLMetrics(bytes: ByteArray): Boolean {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeInstallSMuFLMetrics(SwiftData.fromByteArray(bytes, arena))
    }

    /**
     * Resolve the bounding rectangle (document/mm coordinates) of the cursor
     * identified by [cursorBytes] within the laid-out score [scoreHandle].
     *
     * Returns a 34-byte payload in the CursorFrame wire format on success, or
     * an empty array if the cursor did not resolve (e.g. stale ID after
     * re-layout). Wire format: u16 version (=1), then 4 × i64 micros
     * (x, y, width, height), little-endian.
     */
    fun nativeCursorFrame(
        scoreHandle: Long,
        cursorBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeCursorFrame(
            scoreHandle,
            SwiftData.fromByteArray(cursorBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve the highlight rectangles (mm coordinates) covering a
     * loop region spanning ticks `[fromTick, toTick)`. Returns one
     * rect per intersected system; the rect spans the full staff
     * height of that system and the X range of the included measures.
     *
     * Wire format: u16 version=1, i32 count, count × 4×i64 micros.
     * Empty array when the range yields no measures.
     */
    fun nativeLoopHighlightRects(
        scoreHandle: Long,
        fromTick: Long,
        toTick: Long,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoopHighlightRects(
            scoreHandle,
            fromTick,
            toTick,
            arena,
        ).toByteArray()
    }
}
