package io.github.jiyimeta.sheetmusic

import org.swift.swiftkit.core.SwiftMemoryManagement
import io.github.jiyimeta.sheetmusic.swiftjava.Data as SwiftData
import io.github.jiyimeta.sheetmusic.swiftjava.SheetMusicAndroidJNI as SwiftJavaJNI

/**
 * Thin façade over the JNI entry points generated by swift-java's
 * JExtractSwiftPlugin from `Sources/SheetMusicAndroidJNI/`.
 *
 * `libSheetMusicAndroidJNI.so` and its dependencies (libSwiftJava.so,
 * the Swift runtime) are loaded via the generated swift-java
 * [SheetMusicAndroidJNI]'s static initializer the first time any
 * delegating call below resolves the class.
 */
object SheetMusicJNI {

    /** Returns 0 on parse failure. */
    fun nativeLoadScore(bytes: ByteArray): Long {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadScore(SwiftData.fromByteArray(bytes, arena))
    }

    /**
     * [nativeLoadScore] plus the two things it throws away: the stable dotted
     * fault code for a failure, and the parser's non-fatal diagnostics for a
     * success. Returns a `ScoreLoadResultWire` payload; decode via
     * [ScoreLoadResult.load], which wraps this call.
     *
     * A non-zero `scoreHandle` in the result must be released with
     * [nativeReleaseScore], exactly as [nativeLoadScore]'s return value must.
     */
    fun nativeLoadScoreWithDiagnostics(bytes: ByteArray): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadScoreWithDiagnostics(
            SwiftData.fromByteArray(bytes, arena), arena,
        ).toByteArray()
    }

    /**
     * Parse a MuseScore-exported vector PDF (3.x/4.x) into a score via the
     * Foundation-only pure-Swift PDF reader. Returns 0 on parse failure.
     */
    fun nativeLoadScoreFromPDF(bytes: ByteArray): Long {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadScoreFromPDF(SwiftData.fromByteArray(bytes, arena))
    }

    fun nativeReleaseScore(handle: Long) {
        SwiftJavaJNI.nativeReleaseScore(handle)
    }

    /**
     * `ScoreMetadataWire` payload: `workTitle`, `composer`, and every entry of
     * the score's `metaTags` dictionary, key-sorted. Missing tags come back as
     * zero-length strings; an unknown handle returns an empty array. Decode via
     * [ScoreMetadata.fetch], which wraps this call.
     */
    fun nativeScoreMetadata(handle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeScoreMetadata(handle, arena).toByteArray()
    }

    /**
     * Serialize the score behind [scoreHandle] into `.mscx` or `.mscz` bytes —
     * the counterpart [nativeLoadScore] never had.
     *
     * @param format 0 = `.mscx` (plain XML), 1 = `.mscz` (ZIP container).
     * @param targetVersion 0 for the encoder's default, 3 for the
     *   MuseScore 3 compatibility writer, 4 for MuseScore 4. Any other
     *   value is treated as 0.
     * @param emitPreservedMarkup 0 drops source XML the model does not
     *   represent; anything else keeps it. Preserved markup is source
     *   fidelity, not a semantic guarantee — an edited score can carry a
     *   stale `<Excerpt>` — so a host preparing a file for distribution
     *   passes 0.
     *
     * Returns an empty array for an unknown handle, an unknown format, or an
     * encoding failure.
     */
    fun nativeEncodeScore(
        scoreHandle: Long,
        format: Int,
        targetVersion: Int,
        emitPreservedMarkup: Int,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeEncodeScore(
            scoreHandle, format, targetVersion, emitPreservedMarkup, arena,
        ).toByteArray()
    }

    /**
     * Quarter-note BPM of the score's opening tempo marking (the tempo governing
     * the start), or MuseScore's 120 default. The Reader multiplies this by the
     * playback rate for the inspector's "♩ = N" tempo readout.
     */
    fun nativeOpeningQuarterBpm(scoreHandle: Long): Double =
        SwiftJavaJNI.nativeOpeningQuarterBpm(scoreHandle)

    /**
     * Returns an empty array on failure (e.g. invalid handle or an
     * `optionsBlob` that fails to decode). `optionsBlob` is a
     * `LayoutOptionsWire` payload carrying the layout mode, staff size,
     * break / multi-measure-rest / invisible-element toggles, hidden staves,
     * and clef overrides from the Reader's display inspector.
     */
    fun nativeComputeLayout(
        scoreHandle: Long,
        pageWidthMM: Double,
        pageHeightMM: Double,
        optionsBlob: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeComputeLayout(
            scoreHandle,
            pageWidthMM,
            pageHeightMM,
            SwiftData.fromByteArray(optionsBlob, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Install a SMuFL glyph-metrics table on the Swift side. Returns
     * `true` on success, `false` if the byte format is invalid — a table
     * written for an older format version included, since a stale one
     * would engrave centred glyphs off their baselines. Build it with
     * [FontMetricsBuilder.buildTable]; the wire format spec is on
     * `Sources/SheetMusicBridgeCore/FontMetricsTable.swift`.
     */
    fun nativeInstallSMuFLMetrics(bytes: ByteArray): Boolean {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeInstallSMuFLMetrics(SwiftData.fromByteArray(bytes, arena))
    }

    /**
     * Parts/staves descriptor for the Reader display inspector's Parts section:
     * per part a name + each staff's default clef rawType. Empty array for an
     * unknown handle. Decode via the generated [PartsStavesWireCodec].
     */
    fun nativePartsStaves(handle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePartsStaves(handle, arena).toByteArray()
    }

    /**
     * Resolve the bounding rectangle (document/mm coordinates) of the cursor
     * identified by [cursorBytes] within the laid-out score [scoreHandle].
     *
     * The bytes are **wirelet TLV** — the `@WireFormat` encoding of
     * `CursorFrameCodec.DecodedFrame`, length-prefixed with a tag per field.
     * Decode with the generated
     * `io.github.jiyimeta.sheetmusic.audio.serialization.DecodedFrameCodec`;
     * do NOT read raw doubles out of it, and do not assume a fixed length. An
     * empty array means the cursor did not resolve (e.g. a stale ID after
     * re-layout).
     *
     * (This KDoc used to describe a 34-byte `u16 version` + `4 × i64` micros
     * payload. No part of that was true: the producer says so at the source,
     * and a reader written from it decodes garbage.)
     */
    fun nativeCursorFrame(
        scoreHandle: Long,
        cursorBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeCursorFrame(
            scoreHandle,
            SwiftData.fromByteArray(cursorBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Continuous playback seconds at a possibly fractional UNROLLED player tick.
     *
     * The smooth counterpart of the audio module's `nativeFrameAtTick`, whose `timeSeconds` snaps to
     * a frame onset and therefore steps once per note. A host cannot recover the in-between value by
     * interpolating two polled frame times — those are themselves quantized — so animating a playhead
     * or a scroll needs this entry.
     *
     * [unrolledTick] is in the same coordinates the FluidSynth player reports (repeats and jumps
     * expanded); the fractional part is honoured. Returns **−1** when [scoreHandle] is unknown, which
     * a real position never is — 0 would be indistinguishable from the start of the score.
     */
    fun nativeSecondsAtTick(scoreHandle: Long, unrolledTick: Double): Double =
        SwiftJavaJNI.nativeSecondsAtTick(scoreHandle, unrolledTick)

    /**
     * Bounding rectangle (document/mm coordinates) of the MEASURE the cursor
     * [cursorBytes] sits in — the measure anchor for the horizontal Reader's
     * leading-edge auto-scroll. Same wire format as [nativeCursorFrame]
     * (a single CursorFrame DecodedFrame). Empty array if unresolved.
     */
    fun nativeMeasureFrame(
        scoreHandle: Long,
        cursorBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeMeasureFrame(
            scoreHandle,
            SwiftData.fromByteArray(cursorBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve the nearest playable cursor (a chord onset or a rest) for a tap
     * at ([tapXmm], [tapYmm]) in document/mm coordinates within the laid-out
     * score [scoreHandle]. The hit-test picks the staff closest to the touch,
     * then the nearest event on it, and re-addresses the result against the full
     * (unfiltered) score so the returned cursor drives the audio engine.
     *
     * [hiddenStavesBytes] is the SAME `LayoutOptionsWire` blob passed to
     * [nativeComputeLayout] (only its hidden-staves set is read); reusing it
     * keeps the re-addressing in lockstep with the filtered layout.
     *
     * Returns a `ScoreCursor` wire payload (the format [nativeCursorFrame] /
     * [nativeMeasureFrame] accept back) on a hit, or an empty array when the
     * handle is unknown, the layout is not cached, the options blob fails to
     * decode, or the tap hit no playable element.
     */
    fun nativeNearestCursor(
        scoreHandle: Long,
        tapXmm: Double,
        tapYmm: Double,
        hiddenStavesBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeNearestCursor(
            scoreHandle,
            tapXmm,
            tapYmm,
            SwiftData.fromByteArray(hiddenStavesBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve a freehand-ink point ([xMm], [yMm], document/mm) to a musical
     * anchor (`ResolvedAnchorWire` bytes) in the cached (filtered) layout of
     * [scoreHandle] — the inverse of [nativeAnchorReferencePoint]. Empty array on
     * any miss. Folino's shared anchoring core turns the bytes into a Domain
     * MusicalAnchor and bakes the stroke; no math happens in Kotlin.
     */
    fun nativeResolveAnchor(
        scoreHandle: Long,
        xMm: Double,
        yMm: Double,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeResolveAnchor(
            scoreHandle,
            xMm,
            yMm,
            arena,
        ).toByteArray()
    }

    /**
     * Batched inverse: resolve every anchor identity in [anchorsBytes]
     * (`[AnchorIdentityWire]`) to its document/mm reference point + staff-space
     * (`[AnchorRefPointWire]`; `spMm == 0` sentinel per anchor that did not
     * resolve, so the array stays positionally aligned with the input). One call
     * resolves a whole annotation layer on the reflow/display path. Empty array
     * when the layout is not cached.
     */
    fun nativeAnchorReferencePoint(
        scoreHandle: Long,
        anchorsBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeAnchorReferencePoint(
            scoreHandle,
            SwiftData.fromByteArray(anchorsBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve the highlight rectangles (mm coordinates) covering a
     * loop region spanning ticks `[fromTick, toTick)`. Returns one
     * rect per intersected system; the rect spans the full staff
     * height of that system and the X range of the included measures.
     *
     * The bytes are **wirelet TLV** — a length-prefixed array of
     * `LoopHighlightCodec.Rect`, each entry itself length-prefixed with a tag
     * per field. Decode with the generated
     * `io.github.jiyimeta.sheetmusic.audio.serialization.RectCodec`; there is
     * no version word, no micros scaling and no fixed stride. Empty array when
     * the range yields no measures.
     *
     * (Three mutually inconsistent descriptions of this payload were in
     * circulation — this KDoc's `u16 version` + i64-micros one, the Swift
     * codec's raw-`f64`-array one, and the TLV the reader actually runs. The
     * last is the truth.)
     */
    fun nativeLoopHighlightRects(
        scoreHandle: Long,
        fromTick: Long,
        toTick: Long,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoopHighlightRects(
            scoreHandle,
            fromTick,
            toTick,
            arena,
        ).toByteArray()
    }

    /**
     * Page-break offsets (document-Y, mm) for the cached layout of [scoreHandle], paginated
     * with the same [pageHeightMM] and [optionsBytes] passed to [nativeComputeLayout] so
     * they line up with the `.page` program pages. Wire: i32 count then count × f64, big-endian.
     * `[0, top1, …, contentBottom]`; empty if the handle is unknown.
     */
    fun nativePageBreaks(scoreHandle: Long, pageHeightMM: Double, optionsBytes: ByteArray): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePageBreaks(
            scoreHandle,
            pageHeightMM,
            SwiftData.fromByteArray(optionsBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Rehearsal marks for [scoreHandle], each carrying its text, its 0..1 notated-time
     * fraction (the seek-bar position to align with), and the `ScoreCursor` wire blob to
     * seek to when tapped. An unknown handle returns an empty list payload (the count
     * header is still present). Decode via [RehearsalMarkCodec.decode]. Wire format:
     * `[count:I32 LE]` then per entry `[textLen:I32 LE][textBytes][fraction:F64 LE]
     * [cursorLen:I32 LE][cursorBytes]`.
     */
    fun nativeRehearsalMarks(scoreHandle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeRehearsalMarks(scoreHandle, arena).toByteArray()
    }

    /**
     * Step the engine cursor [fromCursorBytes] by one measure in [direction]
     * (`0 = backward`, `1 = forward`) within [scoreHandle], using the shared
     * `Score.cursorSteppingMeasure` semantics (forward clamps at the last measure;
     * backward restarts the current measure when past its first beat, else jumps to the
     * previous measure's downbeat, clamping at measure 0). [fromCursorBytes] and the
     * result are both `ScoreCursor` wire payloads. Returns [fromCursorBytes] unchanged
     * for an unknown handle or an undecodable input cursor.
     */
    fun nativeStepMeasureCursor(scoreHandle: Long, fromCursorBytes: ByteArray, direction: Int): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeStepMeasureCursor(
            scoreHandle,
            SwiftData.fromByteArray(fromCursorBytes, arena),
            direction,
            arena,
        ).toByteArray()
    }

    /**
     * Advance the cursor [fromCursorBytes] by [beats] quarter-note beats using the shared
     * `Score.cursor(advancedByBeats:from:)` (deterministic notation math). [fromCursorBytes] and the
     * result are both `ScoreCursor` wire payloads. Returns [fromCursorBytes] unchanged for an unknown
     * handle or undecodable input.
     */
    fun nativeCursorAdvancedByBeats(scoreHandle: Long, fromCursorBytes: ByteArray, beats: Double): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeCursorAdvancedByBeats(
            scoreHandle,
            SwiftData.fromByteArray(fromCursorBytes, arena),
            beats,
            arena,
        ).toByteArray()
    }

    /**
     * Parse a MuseScore-exported vector PDF into a score plus its geometry side-car. Returns a
     * `PdfParseResultWire` payload. Empty array on empty input or parse failure. Decode via
     * [PdfParseResultWireCodec]; the caller must release BOTH handles it carries — [nativeReleaseScore]
     * and [nativeReleasePdfGeometry].
     */
    fun nativeLoadScoreWithGeometryFromPDF(bytes: ByteArray): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadScoreWithGeometryFromPDF(
            SwiftData.fromByteArray(bytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Full-height cursor bar for the cursor [cursorBytes] (a `ScoreCursor` wire payload) on the original
     * PDF page identified by [geometryHandle], in top-left page space. Returns a `PdfRectWire` payload.
     * Empty array when the handle is unknown, the cursor doesn't decode, or the column can't be located.
     */
    fun nativePdfCursorRect(geometryHandle: Long, cursorBytes: ByteArray): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePdfCursorRect(
            geometryHandle,
            SwiftData.fromByteArray(cursorBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * Resolve a tap at ([x], [y]) in top-left page space on [pageIndex] of [geometryHandle] to a
     * `ScoreCursor` wire payload the playback bridges accept. Empty array when the handle is unknown or
     * nothing musical is near the tap.
     */
    fun nativePdfHitTest(geometryHandle: Long, pageIndex: Int, x: Double, y: Double): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePdfHitTest(geometryHandle, pageIndex, x, y, arena).toByteArray()
    }

    /**
     * MediaBox sizes indexed positionally by page for [geometryHandle]. Returns a `PdfPageSizesWire`
     * payload. Empty array for an unknown handle. Decode via [PdfPageSizesWireCodec].
     */
    fun nativePdfPageSizes(geometryHandle: Long): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativePdfPageSizes(geometryHandle, arena).toByteArray()
    }

    /**
     * Release a PDF geometry handle obtained from [nativeLoadScoreWithGeometryFromPDF]. Unknown
     * handles are a no-op.
     */
    fun nativeReleasePdfGeometry(handle: Long) {
        SwiftJavaJNI.nativeReleasePdfGeometry(handle)
    }

    /**
     * Opens a mirror edit session over the score behind [scoreHandle]. Returns `false` for an
     * unknown handle. Idempotent: opening twice replaces the session, which is what a host
     * restarting a session wants.
     */
    fun nativeBeginEditSession(scoreHandle: Long): Boolean =
        SwiftJavaJNI.nativeBeginEditSession(scoreHandle)

    /**
     * Relays one edit intent into the mirror session behind [scoreHandle]. Returns `false` when
     * no session is open, the bytes don't decode, or the engine refused the edit.
     *
     * Treat `false` here as an anomaly, not a benign no-op: the authoritative side only ever emits
     * an intent it has already applied, so a refused edit produces no intent and nothing is
     * relayed in the first place. Every intent that reaches this call was already accepted
     * upstream, so `false` can only mean no session is open, the bytes were corrupted in transit,
     * the handle was released mid-edit, or the mirror has already diverged from the authoritative
     * copy. All four call for a resync now, not a log line and a shrug.
     */
    fun nativeApplyEditIntent(scoreHandle: Long, intentBytes: ByteArray): Boolean {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeApplyEditIntent(scoreHandle, SwiftData.fromByteArray(intentBytes, arena))
    }

    /** Undoes the session's last applied intent. Returns `false` when there is no session or nothing to undo. */
    fun nativeEditUndo(scoreHandle: Long): Boolean =
        SwiftJavaJNI.nativeEditUndo(scoreHandle)

    /** Redoes the session's last undone intent. Returns `false` when there is no session or nothing to redo. */
    fun nativeEditRedo(scoreHandle: Long): Boolean =
        SwiftJavaJNI.nativeEditRedo(scoreHandle)

    /**
     * Drops the session behind [scoreHandle]. The score keeps whatever the session last wrote —
     * ending a session is not a revert. A no-op for a handle with no session.
     */
    fun nativeEndEditSession(scoreHandle: Long) {
        SwiftJavaJNI.nativeEndEditSession(scoreHandle)
    }

    /**
     * The digest the host compares against its own copy of [scoreHandle]. `0` for an unknown
     * handle — a value no real score produces often enough to matter, and the host treats
     * "unknown handle" as a mismatch anyway.
     */
    fun nativeScoreFingerprint(scoreHandle: Long): Long =
        SwiftJavaJNI.nativeScoreFingerprint(scoreHandle)

    /** This image's build identity. A host compares it with its own before opening a session. */
    fun nativeEngineVersionStamp(): Long =
        SwiftJavaJNI.nativeEngineVersionStamp()

    /**
     * Editing hit-test at a tap ([xMm], [yMm], document/mm) within the cached (filtered) layout of
     * [scoreHandle], preferring [activeVoice] within the tap's slop box when the raw hit belongs to a
     * different voice. [optionsBytes] is kept for signature parity with [nativeComputeLayout] but is
     * **reserved and ignored**: the hidden-staves set used to re-address the hit against the full score comes
     * from the cache entry the layout was actually computed from, not from this parameter — a caller passing
     * a set that doesn't match what produced the cached layout must not be able to re-address against a
     * mismatched staff set.
     *
     * Returns a `ScoreItemID` wire payload, re-addressed against the full (unfiltered) score so it can be
     * fed straight into an edit intent — or an empty array when the handle is unknown, the layout is not
     * cached, or the tap hit no selectable item.
     *
     * Exception: a tuplet hit keeps its FILTERED staff address (a pre-existing gap in the shared Swift
     * `engineCursorForFilteredTap` re-addressing helper, not specific to this call) — building a tuplet edit
     * intent from this handle with a hidden staff ahead of it in the same part would target the wrong staff.
     * Note/rest hits are unaffected.
     */
    fun nativeEditingHitTest(
        scoreHandle: Long,
        xMm: Double,
        yMm: Double,
        activeVoice: Int,
        optionsBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeEditingHitTest(
            scoreHandle,
            xMm,
            yMm,
            activeVoice,
            SwiftData.fromByteArray(optionsBytes, arena),
            arena,
        ).toByteArray()
    }

    /**
     * The sticky-header pane for a horizontal continuous view: the clef, key
     * signature, time signature and instrument name in force at [scrollXMm],
     * frozen so a reader who has scrolled past bar 1 can still see what key and
     * metre they are in.
     *
     * Returns a **one-page draw program** in exactly the format
     * [nativeComputeLayout] returns, so a host decodes and paints it with the
     * renderer it already has — there is no second drawing path, and a change to
     * how a clef is drawn reaches the pane for free.
     *
     * [scrollXMm] is the viewport's left edge in document millimetres, the same
     * space [nativeEditingHitTest] and [nativeItemIDsInRect] take. Scrolling
     * past the last measure clamps to it rather than emptying the pane.
     *
     * Returns an empty array when the handle is unknown, no layout is cached, or
     * the score has no measures to freeze.
     */
    fun nativeStickyHeaderProgram(scoreHandle: Long, scrollXMm: Double): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeStickyHeaderProgram(scoreHandle, scrollXMm, arena).toByteArray()
    }

    /**
     * Marquee (rubber-band) selection: every chord / rest whose layout box intersects the rectangle
     * ([xMm], [yMm], [widthMm], [heightMm]; document/mm, the same space [nativeEditingHitTest] takes
     * its point in) within the cached layout of [scoreHandle].
     *
     * Returns a `ScoreItemIDListWire` payload — the ids in query order (systems top-to-bottom, then
     * event columns left-to-right), full-score addressed exactly like [nativeEditingHitTest]'s
     * single hit, so the result can be fed straight to [nativeEncodeDrawProgram] or an edit intent.
     *
     * An empty array means "no answer": the handle is unknown or no layout is cached. A rect that
     * covers nothing comes back as a *decodable payload with zero items* — a host that cannot tell
     * the two apart will keep showing a stale selection for a released handle.
     */
    fun nativeItemIDsInRect(
        scoreHandle: Long,
        xMm: Double,
        yMm: Double,
        widthMm: Double,
        heightMm: Double,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeItemIDsInRect(
            scoreHandle, xMm, yMm, widthMm, heightMm, arena,
        ).toByteArray()
    }

    /**
     * Insertion-caret rect (document/mm) for [itemBytes] (a `ScoreItemID` wire payload, full-score
     * addressed — the same value [nativeEditingHitTest] returns) within the cached layout of
     * [scoreHandle], narrowed to the item's own staff band. [minimumWidthMm] floors a zero-width frame;
     * pass 0 for no floor.
     *
     * Returns an `EditCaretFrameWire` payload (`xMm`/`yMm`/`widthMm`/`heightMm`), or an empty array when
     * the handle is unknown, the layout is not cached, the item bytes fail to decode, or the item doesn't
     * resolve to a laid-out frame (e.g. a stale ID right after an edit reflows the document).
     */
    fun nativeEditingCaretFrame(
        scoreHandle: Long,
        itemBytes: ByteArray,
        minimumWidthMm: Double,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeEditingCaretFrame(
            scoreHandle,
            SwiftData.fromByteArray(itemBytes, arena),
            minimumWidthMm,
            arena,
        ).toByteArray()
    }

    /**
     * Re-encodes the ALREADY-CACHED layout of [scoreHandle] as a draw-program payload with
     * [selectionBytes] (a `SelectionTintCodec` payload: packed ARGB color + full-score-addressed
     * `ScoreItemID`s) tinted — a tuplet selection is expanded to every member note/rest its bracket spans.
     * Never relayouts: an empty cache (no prior [nativeComputeLayout] call for this handle) returns an
     * empty array, so call [nativeComputeLayout] first. Same wire format [nativeComputeLayout] returns, and
     * reproduces its page count and per-page dimensions exactly in every layout mode (the cache carries the
     * `LayoutOptionsWire` and page size [nativeComputeLayout] was called with, so `.vertical`'s viewport
     * width and `.page`'s multi-page split are replayed, not approximated) — an empty selection reproduces
     * [nativeComputeLayout]'s bytes exactly.
     */
    fun nativeEncodeDrawProgram(
        scoreHandle: Long,
        selectionBytes: ByteArray,
    ): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeEncodeDrawProgram(
            scoreHandle,
            SwiftData.fromByteArray(selectionBytes, arena),
            arena,
        ).toByteArray()
    }
}
