// Emits the fixtures `Web/sheet-music-web/test/` reads.
//
// Three files, all generated by the Apple build so the browser has something
// authored elsewhere to be checked against:
//
//   all-opcodes.smdf        — a DrawProgramFlat payload carrying every opcode,
//                             so the TypeScript decoder is tested against bytes
//                             the Swift encoder actually produced rather than
//                             bytes a test author hand-assembled.
//   sample.mscz             — a small score a browser can load.
//   sample-expectations.json — what the Apple build computes for it.
//
// `Score.stableFingerprint` is FNV-1a with fixed constants and no per-process
// seed, and the draw program is deterministic, so the wasm build must produce
// identical output from the same input. That equality is the only thing standing
// behind "the browser engraves what the app engraves", so it is checked against
// numbers generated here rather than numbers a test author typed.
//
// The score is built in code rather than copied from
// Tests/SheetMusicTests/Resources: those fixtures are GPL-3.0 copies of
// MuseScore's own and must stay confined to the test target — see CLAUDE.md.
//
//     swift run GenWebFixtures \
//         Web/sheet-music-web/test/fixtures \
//         Web/sheet-music-web/assets/bravura.smft
import Foundation
import SheetMusicBridgeCore
import SheetMusicCore
import SheetMusicLayout
import SheetMusicLayoutApple
import SheetMusicMSCX

enum GenWebFixtures {
    /// The page `Tests/SheetMusicTests/DrawProgramFlatTests.swift` round-trips,
    /// duplicated here on purpose: if the two ever diverge, a decoder
    /// disagreement stops being attributable to one side.
    static var allOpcodesPage: EncodablePage {
        EncodablePage(
            widthMM: 210,
            heightMM: 297,
            commands: [
                .moveTo(x: 1, y: 2),
                .lineTo(x: 3, y: 4),
                .stroke(width: 0.5),
                .fillRect(x: 5, y: 6, w: 7, h: 8),
                .glyph(codepoint: 0xE050, x: 9, y: 10, size: 11, fontId: .smufl),
                .text(text: "Allegro", x: 12, y: 13, size: 14, fontId: .textRoman),
                .setColor(argb: 0xFF00_7AFF),
                .cubicTo(cx1: 15, cy1: 16, cx2: 17, cy2: 18, x: 19, y: 20),
                .stretchedGlyph(
                    codepoint: 0xE000, rightEdgeX: 21, topY: 22, bottomY: 23,
                    fontSize: 24, xScale: 1.5, fontId: .smufl,
                ),
                .setRotation(radians: 1.5707963267948966, pivotX: 25, pivotY: 26),
                .setDash(onMM: 0.75, offMM: 0.25),
                .italicText(text: "3", x: 27, y: 28, size: 29, fontId: .textRoman),
            ],
        )
    }

    /// A score with one staff and four quarter notes. Notes rather than an empty
    /// frame because a score with nothing to engrave lays out to zero systems,
    /// and a fixture that draws nothing tests nothing.
    static var sampleScore: Score {
        let elements = [60, 62, 64, 65].map { pitch in
            VoiceElement.chord(
                Chord(duration: .quarter, notes: ChordNotes([Note(pitch: pitch, tpc: 14)])),
            )
        }
        return Score(
            division: 480,
            parts: [
                Part(
                    id: "1",
                    instrument: Instrument(id: "piano", longName: "Piano"),
                    staves: [Staff(measures: [Measure(voices: [Voice(elements: elements)])])],
                ),
            ],
            metaTags: ["workTitle": "web parity", "composer": "swift-sheet-music"],
            titleFrame: ScoreFrame(
                heightSp: 10,
                texts: [FrameText(style: .title, text: "web parity")],
            ),
        )
    }

    /// FNV-1a, 32-bit. A digest rather than the payload itself: the test only
    /// needs to detect divergence, and committing a multi-hundred-KB blob would
    /// make every engraving change look like a fixture conflict. 32-bit so the
    /// TypeScript side can compute the same value with `Math.imul` and no
    /// `BigInt`.
    static func digest(_ bytes: Data) -> UInt32 {
        var hash: UInt32 = 2_166_136_261
        for byte in bytes {
            hash ^= UInt32(byte)
            hash &*= 16_777_619
        }
        return hash
    }

    struct Expectations: Encodable {
        let title: String
        let composer: String
        let partCount: Int
        let staffCount: Int
        let openingQuarterBpm: Double
        /// Decimal string, matching the wasm surface: the digest is 64 bits, and
        /// a JSON number is an f64 that would round it.
        let fingerprint: String
        let flatByteCount: Int
        let flatDigest: UInt32
        let pageCount: Int
        let firstPageWidthMM: Double
        let firstPageCommandCount: Int
    }

    static func fail(_ message: String, code: Int32) -> Never {
        FileHandle.standardError.write(Data("error: \(message)\n".utf8))
        exit(code)
    }

    /// Installs the same `bravura.smft` table the browser installs, NOT the
    /// CoreText provider.
    ///
    /// The table is generated from CoreText but is not identical to it: values
    /// are stored as `Float` at a 1000 pt reference size and rescaled at lookup,
    /// so glyph positions differ in their low bits. Engraving through CoreText
    /// here and through the table in the browser produces draw programs of the
    /// same length and shape whose bytes differ — which is a true statement
    /// about two different providers and says nothing about whether the
    /// WebAssembly build is correct.
    ///
    /// Pinning both sides to the same provider is what makes byte equality
    /// meaningful: any difference that survives is a difference between the
    /// native and WebAssembly *engines*, which is what this fixture is for.
    static func installSharedMetrics(tableURL: URL) {
        guard #available(macOS 15.0, *) else {
            fail("macOS 15 or newer required", code: 1)
        }
        _ = SheetMusicLayoutApple.install
        guard BravuraFont.register else {
            fail("Bravura failed to register with CoreText", code: 4)
        }
        do {
            let table = try SMuFLMetricsTable.decode(Data(contentsOf: tableURL))
            FontMetrics.provider = makeSMuFLMetricsTableProvider(table: table)
        } catch {
            fail("could not install \(tableURL.path): \(error)", code: 8)
        }
    }

    static func makeExpectations(
        score: Score,
        pages: [EncodablePage],
        flat: Data,
    ) -> Expectations {
        guard let firstPage = pages.first else {
            fail("the sample score laid out to no pages", code: 6)
        }
        return Expectations(
            title: score.metaTags["workTitle"] ?? "",
            composer: score.metaTags["composer"] ?? "",
            partCount: score.parts.count,
            staffCount: score.parts.reduce(0) { $0 + $1.staves.count },
            openingQuarterBpm: score.openingQuarterBpm,
            fingerprint: String(score.stableFingerprint),
            flatByteCount: flat.count,
            flatDigest: digest(flat),
            pageCount: pages.count,
            firstPageWidthMM: firstPage.widthMM,
            firstPageCommandCount: firstPage.commands.count,
        )
    }

    static func write(
        opcodes: Data,
        container: Data,
        expectations: Expectations,
        to directory: URL,
    ) {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        do {
            try FileManager.default.createDirectory(
                at: directory, withIntermediateDirectories: true,
            )
            try opcodes.write(to: directory.appendingPathComponent("all-opcodes.smdf"))
            try container.write(to: directory.appendingPathComponent("sample.mscz"))
            try encoder.encode(expectations)
                .write(to: directory.appendingPathComponent("sample-expectations.json"))
        } catch {
            fail("could not write fixtures to \(directory.path): \(error)", code: 7)
        }
    }

    static func run() {
        guard CommandLine.arguments.count == 3 else {
            FileHandle.standardError.write(
                Data("usage: GenWebFixtures <output-dir> <bravura.smft>\n".utf8),
            )
            exit(2)
        }
        let directory = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
        installSharedMetrics(tableURL: URL(fileURLWithPath: CommandLine.arguments[2]))

        let opcodes = DrawProgramFlat.encode(pages: [
            allOpcodesPage,
            EncodablePage(widthMM: 100, heightMM: 50, commands: []),
        ])

        let container: Data
        let reloaded: Score
        do {
            container = try MSCZWriter.write(score: sampleScore)
            reloaded = try ScoreBridge.loadScore(bytes: container)
        } catch {
            fail("could not round-trip the sample score: \(error)", code: 5)
        }

        let result = LayoutBridge.computeWithPages(
            score: reloaded, pageWidthMM: 210, pageHeightMM: 297, options: .verticalDefault,
        )
        let flat = DrawProgramFlat.encode(pages: result.pages)
        let expectations = makeExpectations(score: reloaded, pages: result.pages, flat: flat)
        write(
            opcodes: opcodes, container: container, expectations: expectations, to: directory,
        )

        print(
            "wrote all-opcodes.smdf (\(opcodes.count)B), sample.mscz (\(container.count)B), "
                + "sample-expectations.json — \(flat.count)B flat over "
                + "\(expectations.pageCount) page(s), "
                + "\(expectations.firstPageCommandCount) commands",
        )

        // The playback fixture goes through the same container round trip: the
        // browser loads a `.mscz`, so the expectations have to be computed from
        // the score that comes back out of one rather than the one built above.
        let repeatContainer: Data
        let repeatReloaded: Score
        do {
            repeatContainer = try MSCZWriter.write(score: repeatScore)
            repeatReloaded = try ScoreBridge.loadScore(bytes: repeatContainer)
        } catch {
            fail("could not round-trip the repeat score: \(error)", code: 5)
        }
        let playback = makePlaybackExpectations(score: repeatReloaded)
        writePlayback(
            container: repeatContainer, expectations: playback, to: directory,
        )

        print(
            "wrote repeat.mscz (\(repeatContainer.count)B), repeat-playback.json — "
                + "\(playback.measureCount) measure(s), "
                + "notated \(playback.totalNotatedSeconds)s vs player "
                + "\(playback.totalPlayerSeconds)s, "
                + "midi \(playback.midiByteCount)B",
        )
    }
}

GenWebFixtures.run()
