// Emits the fixtures `Web/sheet-music-web/test/` reads.
//
// Three files, all generated by the Apple build so the browser has something
// authored elsewhere to be checked against:
//
//   all-opcodes.smdf        — a DrawProgramFlat payload carrying every opcode,
//                             so the TypeScript decoder is tested against bytes
//                             the Swift encoder actually produced rather than
//                             bytes a test author hand-assembled.
//   sample.mscz             — a small score a browser can load.
//   sample-expectations.json — what the Apple build computes for it.
//
// `Score.stableFingerprint` is FNV-1a with fixed constants and no per-process
// seed, and the draw program is deterministic, so the wasm build must produce
// identical output from the same input. That equality is the only thing standing
// behind "the browser engraves what the app engraves", so it is checked against
// numbers generated here rather than numbers a test author typed.
//
// The score is built in code rather than copied from
// Tests/SheetMusicTests/Resources: those fixtures are GPL-3.0 copies of
// MuseScore's own and must stay confined to the test target — see CLAUDE.md.
//
// Checks the committed fixtures by default and exits non-zero when one has
// drifted; `SM_WEB_FIXTURE_RECORD=1` rewrites them instead. See
// `FixtureEmitter` for why the check is a process rather than a test.
//
//     swift run GenWebFixtures \
//         Web/sheet-music-web/test/fixtures \
//         Web/sheet-music-web/assets/sheet-music.smft
//
//     SM_WEB_FIXTURE_RECORD=1 swift run GenWebFixtures \
//         Web/sheet-music-web/test/fixtures \
//         Web/sheet-music-web/assets/sheet-music.smft
import Foundation
import SheetMusicBridgeCore
import SheetMusicCore
import SheetMusicLayout
import SheetMusicLayoutApple
import SheetMusicMSCX

enum GenWebFixtures {
    /// The page `Tests/SheetMusicTests/DrawProgramFlatTests.swift` round-trips,
    /// duplicated here on purpose: if the two ever diverge, a decoder
    /// disagreement stops being attributable to one side.
    static var allOpcodesPage: EncodablePage {
        EncodablePage(
            widthMM: 210,
            heightMM: 297,
            commands: [
                .moveTo(x: 1, y: 2),
                .lineTo(x: 3, y: 4),
                .stroke(width: 0.5),
                .fillRect(x: 5, y: 6, w: 7, h: 8),
                .glyph(codepoint: 0xE050, x: 9, y: 10, size: 11, fontId: .smufl),
                .text(text: "Allegro", x: 12, y: 13, size: 14, fontId: .textRoman),
                .setColor(argb: 0xFF00_7AFF),
                .cubicTo(cx1: 15, cy1: 16, cx2: 17, cy2: 18, x: 19, y: 20),
                .stretchedGlyph(
                    codepoint: 0xE000, rightEdgeX: 21, topY: 22, bottomY: 23,
                    fontSize: 24, xScale: 1.5, fontId: .smufl,
                ),
                .setRotation(radians: 1.5707963267948966, pivotX: 25, pivotY: 26),
                .setDash(onMM: 0.75, offMM: 0.25),
                .italicText(text: "3", x: 27, y: 28, size: 29, fontId: .textRoman),
            ],
        )
    }

    /// A score with one staff and four quarter notes. Notes rather than an empty
    /// frame because a score with nothing to engrave lays out to zero systems,
    /// and a fixture that draws nothing tests nothing.
    static var sampleScore: Score {
        let elements = [60, 62, 64, 65].map { pitch in
            VoiceElement.chord(
                Chord(duration: .quarter, notes: ChordNotes([Note(pitch: pitch, tpc: 14)])),
            )
        }
        return Score(
            division: 480,
            parts: [
                Part(
                    id: "1",
                    instrument: Instrument(id: "piano", longName: "Piano"),
                    staves: [Staff(measures: [Measure(voices: [Voice(elements: elements)])])],
                ),
            ],
            metaTags: ["workTitle": "web parity", "composer": "swift-sheet-music"],
            titleFrame: ScoreFrame(
                heightSp: 10,
                texts: [FrameText(style: .title, text: "web parity")],
            ),
        )
    }

    /// FNV-1a, 32-bit. A digest rather than the payload itself: the test only
    /// needs to detect divergence, and committing a multi-hundred-KB blob would
    /// make every engraving change look like a fixture conflict. 32-bit so the
    /// TypeScript side can compute the same value with `Math.imul` and no
    /// `BigInt`.
    static func digest(_ bytes: Data) -> UInt32 {
        var hash: UInt32 = 2_166_136_261
        for byte in bytes {
            hash ^= UInt32(byte)
            hash &*= 16_777_619
        }
        return hash
    }

    struct Expectations: Encodable {
        let title: String
        let composer: String
        let partCount: Int
        let staffCount: Int
        let openingQuarterBpm: Double
        /// Decimal string, matching the wasm surface: the digest is 64 bits, and
        /// a JSON number is an f64 that would round it.
        let fingerprint: String
        let flatByteCount: Int
        let flatDigest: UInt32
        let pageCount: Int
        let firstPageWidthMM: Double
        let firstPageCommandCount: Int
    }

    struct TallExpectations: Encodable {
        let flatByteCount: Int
        let flatDigest: UInt32
        let pageCount: Int
        let pageHeightMM: Double
        let commandCount: Int
    }

    /// A single-staff score tall enough for band culling to be observable.
    static var tallScore: Score {
        let measures = (0 ..< 200).map { index in
            Measure(voices: [
                Voice(elements: [
                    .chord(Chord(
                        duration: .whole,
                        notes: ChordNotes([Note(pitch: 60 + index % 8, tpc: 14)]),
                    )),
                ]),
            ])
        }
        return Score(
            division: 480,
            parts: [
                Part(
                    id: "1",
                    instrument: Instrument(id: "piano", longName: "Piano"),
                    staves: [Staff(measures: measures)],
                ),
            ],
            metaTags: ["workTitle": "web tall", "composer": "swift-sheet-music"],
        )
    }

    static func fail(_ message: String, code: Int32) -> Never {
        FileHandle.standardError.write(Data("error: \(message)\n".utf8))
        exit(code)
    }

    /// Installs the same `sheet-music.smft` table the browser installs, NOT the
    /// CoreText provider.
    ///
    /// The table is generated from CoreText but is not identical to it: values
    /// are stored as `Float` at a 1000 pt reference size and rescaled at lookup,
    /// so glyph positions differ in their low bits. Engraving through CoreText
    /// here and through the table in the browser produces draw programs of the
    /// same length and shape whose bytes differ — which is a true statement
    /// about two different providers and says nothing about whether the
    /// WebAssembly build is correct.
    ///
    /// Pinning both sides to the same provider is what makes byte equality
    /// meaningful: any difference that survives is a difference between the
    /// native and WebAssembly *engines*, which is what this fixture is for.
    static func installSharedMetrics(tableURL: URL) {
        guard #available(macOS 15.0, *) else {
            fail("macOS 15 or newer required", code: 1)
        }
        _ = SheetMusicLayoutApple.install
        guard BravuraFont.register else {
            fail("Bravura failed to register with CoreText", code: 4)
        }
        do {
            let table = try FontMetricsTable.decode(Data(contentsOf: tableURL))
            FontMetrics.provider = makeFontMetricsTableProvider(table: table)
        } catch {
            fail("could not install \(tableURL.path): \(error)", code: 8)
        }
    }

    static func makeExpectations(
        score: Score,
        pages: [EncodablePage],
        flat: Data,
    ) -> Expectations {
        guard let firstPage = pages.first else {
            fail("the sample score laid out to no pages", code: 6)
        }
        return Expectations(
            title: score.metaTags["workTitle"] ?? "",
            composer: score.metaTags["composer"] ?? "",
            partCount: score.parts.count,
            staffCount: score.parts.reduce(0) { $0 + $1.staves.count },
            openingQuarterBpm: score.openingQuarterBpm,
            fingerprint: String(score.stableFingerprint),
            flatByteCount: flat.count,
            flatDigest: digest(flat),
            pageCount: pages.count,
            firstPageWidthMM: firstPage.widthMM,
            firstPageCommandCount: firstPage.commands.count,
        )
    }

    static func write(
        opcodes: Data,
        container: Data,
        expectations: Expectations,
        editExpectations: SampleEditExpectations,
        to directory: URL,
    ) {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        do {
            try FileManager.default.createDirectory(
                at: directory, withIntermediateDirectories: true,
            )
            try FixtureEmitter.emit(opcodes, as: "all-opcodes.smdf", in: directory)
            try FixtureEmitter.emit(container, as: "sample.mscz", in: directory)
            try FixtureEmitter.emit(
                encoder.encode(expectations), as: "sample-expectations.json", in: directory,
            )
            try FixtureEmitter.emit(
                encoder.encode(editExpectations),
                as: "sample-edit-expectations.json",
                in: directory,
            )
        } catch {
            fail("could not write fixtures to \(directory.path): \(error)", code: 7)
        }
    }

    static func writeTallScore(to directory: URL) {
        let container: Data
        let reloaded: Score
        do {
            container = try MSCZWriter.write(score: tallScore)
            reloaded = try ScoreBridge.loadScore(bytes: container)
        } catch {
            fail("could not round-trip the tall score: \(error)", code: 5)
        }

        let result = LayoutBridge.computeWithPages(
            score: reloaded, pageWidthMM: 210, pageHeightMM: 297, options: .verticalDefault,
        )
        guard let page = result.pages.first else {
            fail("the tall score laid out to no pages", code: 6)
        }
        let flat = DrawProgramFlat.encode(pages: result.pages)
        let expectations = TallExpectations(
            flatByteCount: flat.count,
            flatDigest: digest(flat),
            pageCount: result.pages.count,
            pageHeightMM: page.heightMM,
            commandCount: page.commands.count,
        )

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        do {
            try FixtureEmitter.emit(container, as: "tall.mscz", in: directory)
            try FixtureEmitter.emit(flat, as: "tall.smdf", in: directory)
            try FixtureEmitter.emit(
                encoder.encode(expectations), as: "tall-expectations.json", in: directory,
            )
        } catch {
            fail("could not write tall fixtures to \(directory.path): \(error)", code: 12)
        }

        print(
            "\(FixtureEmitter.verb) tall.mscz (\(container.count)B), tall.smdf (\(flat.count)B), "
                + "tall-expectations.json — \(expectations.pageHeightMM)mm, "
                + "\(expectations.commandCount) commands",
        )
    }

    static func run() {
        guard CommandLine.arguments.count == 3 else {
            FileHandle.standardError.write(
                Data(
                    """
                    usage: GenWebFixtures <fixture-dir> <sheet-music.smft>
                    checks the committed fixtures; \
                    \(FixtureEmitter.recordVariable)=1 rewrites them

                    """.utf8,
                ),
            )
            exit(2)
        }
        let directory = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
        installSharedMetrics(tableURL: URL(fileURLWithPath: CommandLine.arguments[2]))

        writeSampleFixtures(to: directory)
        writeRepeatFixtures(to: directory)
        writeMixerScore(to: directory)
        writeTallScore(to: directory)
        FixtureEmitter.finish()
    }

    /// The draw-program and sample-score half: every opcode, plus a score small
    /// enough that a decoder disagreement is readable in the diff.
    private static func writeSampleFixtures(to directory: URL) {
        let opcodes = DrawProgramFlat.encode(pages: [
            allOpcodesPage,
            EncodablePage(widthMM: 100, heightMM: 50, commands: []),
        ])

        let container: Data
        let reloaded: Score
        do {
            container = try MSCZWriter.write(score: sampleScore)
            reloaded = try ScoreBridge.loadScore(bytes: container)
        } catch {
            fail("could not round-trip the sample score: \(error)", code: 5)
        }

        let result = LayoutBridge.computeWithPages(
            score: reloaded, pageWidthMM: 210, pageHeightMM: 297, options: .verticalDefault,
        )
        let flat = DrawProgramFlat.encode(pages: result.pages)
        let expectations = makeExpectations(score: reloaded, pages: result.pages, flat: flat)
        let editExpectations = makeSampleEditExpectations(score: reloaded, document: result.document)
        write(
            opcodes: opcodes,
            container: container,
            expectations: expectations,
            editExpectations: editExpectations,
            to: directory,
        )

        print(
            "\(FixtureEmitter.verb) all-opcodes.smdf (\(opcodes.count)B), "
                + "sample.mscz (\(container.count)B), "
                + "sample-expectations.json, sample-edit-expectations.json — \(flat.count)B flat over "
                + "\(expectations.pageCount) page(s), "
                + "\(expectations.firstPageCommandCount) commands",
        )
    }
}

GenWebFixtures.run()
